!!****f* ABINIT/ptg_C1
!!
!! NAME
!! ptg_C1
!!
!! FUNCTION
!!
!! COPYRIGHT
!! Copyright (C) 2010-2019 ABINIT group (MG)
!! This file is distributed under the terms of the
!! GNU General Public License, see ~abinit/COPYING
!! or http://www.gnu.org/copyleft/gpl.txt .
!! For the initials of contributors, see ~abinit/doc/developers/contributors.txt .
!!
!! INPUTS
!!
!! OUTPUT
!!
!! PARENTS
!!      m_ptgroups
!!
!! CHILDREN
!!
!! SOURCE
!!
!********************************************************************************
! This include file has been automatically generated by the script ptg.py
! Do not edit! Change the script source instead.
!********************************************************************************

! Point group name  C1 (1)

#if defined HAVE_CONFIG_H
#include "config.h"
#endif

#include "abi_common.h"

module m_ptg_C1

contains
!!***

 subroutine ptg_C1 (nsym,nclass,sym,class_ids,class_names,Irr)
 use defs_basis
 use m_abicore
 use m_defs_ptgroups,  only : irrep_t
 implicit none

!Arguments ------------------------------------
 integer,intent(out) :: nclass,nsym
 !arrays
 integer,allocatable,intent(out) :: sym(:,:,:), class_ids(:,:)
 character(len=5),allocatable,intent(out) :: class_names(:)
 type(irrep_t),allocatable,intent(out) :: Irr(:)
 !Local variables-------------------------------
 complex(dpc) :: j=(0.0_dp,1.0_dp)
 ! ********************************************************************************
! List of symmetries packed in classes
 nsym = 1
 ABI_MALLOC(sym, (3,3,nsym))
 sym(:,:,1) = RESHAPE( (/1, 0, 0, 0, 1, 0, 0, 0, 1/) ,(/3,3/) )

! Number of classes and corresponding indeces
 nclass = 1
 ABI_MALLOC(class_ids, (2,nclass))
 class_ids(1,1) = 1
 class_ids(2,1) = 1

ABI_MALLOC(class_names,(1))
 class_names(1) = "1+"

! List of irreducible representations.
 ABI_DT_MALLOC(Irr, (1))
 Irr(1)%name = "A"
 Irr(1)%dim = 1
 Irr(1)%nsym = 1
 ABI_MALLOC(Irr(1)%mat, (1,1,1))
 Irr(1)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )

 RETURN
  if (.FALSE.) write(std_out,*) j
 end subroutine ptg_C1
!!***

end module m_ptg_C1
!!***
