!!****f* ABINIT/ptg_C6h
!!
!! NAME
!! ptg_C6h
!!
!! FUNCTION
!!
!! COPYRIGHT
!! Copyright (C) 2010-2020 ABINIT group (MG)
!! This file is distributed under the terms of the
!! GNU General Public License, see ~abinit/COPYING
!! or http://www.gnu.org/copyleft/gpl.txt .
!! For the initials of contributors, see ~abinit/doc/developers/contributors.txt .
!!
!! INPUTS
!!
!! OUTPUT
!!
!! PARENTS
!!      m_ptgroups
!!
!! CHILDREN
!!
!! SOURCE
!!
!********************************************************************************
! This include file has been automatically generated by the script ptg.py
! Do not edit! Change the script source instead.
!********************************************************************************

! Point group name  C6h (6/m)

#if defined HAVE_CONFIG_H
#include "config.h"
#endif

#include "abi_common.h"


module m_ptg_C6h
contains
!!**



 subroutine ptg_C6h (nsym,nclass,sym,class_ids,class_names,Irr)
 use defs_basis
 use m_abicore
 use m_defs_ptgroups,  only : irrep_t
 implicit none
!Arguments ------------------------------------
 integer,intent(out) :: nclass,nsym 
 !arrays
 integer,allocatable,intent(out) :: sym(:,:,:), class_ids(:,:)
 character(len=5),allocatable,intent(out) :: class_names(:)
 type(irrep_t),allocatable,intent(out) :: Irr(:)
 !Local variables-------------------------------
 complex(dpc) :: j=(0.0_dp,1.0_dp) 
 ! ********************************************************************************
! List of symmetries packed in classes
 nsym = 12
 ABI_MALLOC(sym, (3,3,nsym))
 sym(:,:,1) = RESHAPE( (/1, 0, 0, 0, 1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,2) = RESHAPE( (/0, 1, 0, -1, -1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,3) = RESHAPE( (/-1, -1, 0, 1, 0, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,4) = RESHAPE( (/-1, 0, 0, 0, -1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,5) = RESHAPE( (/0, -1, 0, 1, 1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,6) = RESHAPE( (/1, 1, 0, -1, 0, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,7) = RESHAPE( (/-1, 0, 0, 0, -1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,8) = RESHAPE( (/0, -1, 0, 1, 1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,9) = RESHAPE( (/1, 1, 0, -1, 0, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,10) = RESHAPE( (/1, 0, 0, 0, 1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,11) = RESHAPE( (/0, 1, 0, -1, -1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,12) = RESHAPE( (/-1, -1, 0, 1, 0, 0, 0, 0, -1/) ,(/3,3/) )

! Number of classes and corresponding indeces
 nclass = 12
 ABI_MALLOC(class_ids, (2,nclass))
 class_ids(1,1) = 1
 class_ids(2,1) = 1
 class_ids(1,2) = 2
 class_ids(2,2) = 2
 class_ids(1,3) = 3
 class_ids(2,3) = 3
 class_ids(1,4) = 4
 class_ids(2,4) = 4
 class_ids(1,5) = 5
 class_ids(2,5) = 5
 class_ids(1,6) = 6
 class_ids(2,6) = 6
 class_ids(1,7) = 7
 class_ids(2,7) = 7
 class_ids(1,8) = 8
 class_ids(2,8) = 8
 class_ids(1,9) = 9
 class_ids(2,9) = 9
 class_ids(1,10) = 10
 class_ids(2,10) = 10
 class_ids(1,11) = 11
 class_ids(2,11) = 11
 class_ids(1,12) = 12
 class_ids(2,12) = 12

ABI_MALLOC(class_names,(12))
 class_names(1) = "1+" 
 class_names(2) = "3+" 
 class_names(3) = "3+" 
 class_names(4) = "2+" 
 class_names(5) = "6+" 
 class_names(6) = "6+" 
 class_names(7) = "-2-" 
 class_names(8) = "-6-" 
 class_names(9) = "-6-" 
 class_names(10) = "-2+" 
 class_names(11) = "-6+" 
 class_names(12) = "-6+" 

! List of irreducible representations.
 ABI_DT_MALLOC(Irr, (12))
 Irr(1)%name = "Ag"
 Irr(1)%dim = 1
 Irr(1)%nsym = 12
 ABI_MALLOC(Irr(1)%mat, (1,1,12))
 Irr(1)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,5) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,6) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,8) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,9) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,11) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,12) =  RESHAPE( (/1.0/), (/1, 1/) )

 Irr(2)%name = "Au"
 Irr(2)%dim = 1
 Irr(2)%nsym = 12
 ABI_MALLOC(Irr(2)%mat, (1,1,12))
 Irr(2)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,5) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,6) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,8) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,9) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,11) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,12) =  RESHAPE( (/-1.0/), (/1, 1/) )

 Irr(3)%name = "Bg"
 Irr(3)%dim = 1
 Irr(3)%nsym = 12
 ABI_MALLOC(Irr(3)%mat, (1,1,12))
 Irr(3)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,5) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,6) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,8) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,9) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,11) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,12) =  RESHAPE( (/-1.0/), (/1, 1/) )

 Irr(4)%name = "Bu"
 Irr(4)%dim = 1
 Irr(4)%nsym = 12
 ABI_MALLOC(Irr(4)%mat, (1,1,12))
 Irr(4)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,5) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,6) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,8) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,9) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,11) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,12) =  RESHAPE( (/1.0/), (/1, 1/) )

 Irr(5)%name = "E2g2"
 Irr(5)%dim = 1
 Irr(5)%nsym = 12
 ABI_MALLOC(Irr(5)%mat, (1,1,12))
 Irr(5)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(5)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(5)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,5) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(5)%mat(:,:,6) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(5)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,8) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(5)%mat(:,:,9) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(5)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,11) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(5)%mat(:,:,12) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )

 Irr(6)%name = "E2u2"
 Irr(6)%dim = 1
 Irr(6)%nsym = 12
 ABI_MALLOC(Irr(6)%mat, (1,1,12))
 Irr(6)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(6)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(6)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,5) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(6)%mat(:,:,6) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(6)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,8) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(6)%mat(:,:,9) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(6)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,11) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(6)%mat(:,:,12) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )

 Irr(7)%name = "E1g1"
 Irr(7)%dim = 1
 Irr(7)%nsym = 12
 ABI_MALLOC(Irr(7)%mat, (1,1,12))
 Irr(7)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(7)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(7)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,5) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(7)%mat(:,:,6) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(7)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,8) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(7)%mat(:,:,9) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(7)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,11) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(7)%mat(:,:,12) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )

 Irr(8)%name = "E1u1"
 Irr(8)%dim = 1
 Irr(8)%nsym = 12
 ABI_MALLOC(Irr(8)%mat, (1,1,12))
 Irr(8)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(8)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(8)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,5) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(8)%mat(:,:,6) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(8)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,8) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(8)%mat(:,:,9) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(8)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,11) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(8)%mat(:,:,12) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )

 Irr(9)%name = "E2g1"
 Irr(9)%dim = 1
 Irr(9)%nsym = 12
 ABI_MALLOC(Irr(9)%mat, (1,1,12))
 Irr(9)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(9)%mat(:,:,2) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(9)%mat(:,:,3) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(9)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(9)%mat(:,:,5) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(9)%mat(:,:,6) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(9)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(9)%mat(:,:,8) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(9)%mat(:,:,9) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(9)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(9)%mat(:,:,11) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(9)%mat(:,:,12) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )

 Irr(10)%name = "E2u1"
 Irr(10)%dim = 1
 Irr(10)%nsym = 12
 ABI_MALLOC(Irr(10)%mat, (1,1,12))
 Irr(10)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(10)%mat(:,:,2) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(10)%mat(:,:,3) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(10)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(10)%mat(:,:,5) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(10)%mat(:,:,6) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(10)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(10)%mat(:,:,8) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(10)%mat(:,:,9) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(10)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(10)%mat(:,:,11) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(10)%mat(:,:,12) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )

 Irr(11)%name = "E1g2"
 Irr(11)%dim = 1
 Irr(11)%nsym = 12
 ABI_MALLOC(Irr(11)%mat, (1,1,12))
 Irr(11)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(11)%mat(:,:,2) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(11)%mat(:,:,3) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(11)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(11)%mat(:,:,5) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(11)%mat(:,:,6) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(11)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(11)%mat(:,:,8) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(11)%mat(:,:,9) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(11)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(11)%mat(:,:,11) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(11)%mat(:,:,12) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )

 Irr(12)%name = "E1u2"
 Irr(12)%dim = 1
 Irr(12)%nsym = 12
 ABI_MALLOC(Irr(12)%mat, (1,1,12))
 Irr(12)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(12)%mat(:,:,2) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(12)%mat(:,:,3) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )
 Irr(12)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(12)%mat(:,:,5) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(12)%mat(:,:,6) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(12)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(12)%mat(:,:,8) =  RESHAPE( (/0.5+0.86603*j/), (/1, 1/) )
 Irr(12)%mat(:,:,9) =  RESHAPE( (/0.5-0.86603*j/), (/1, 1/) )
 Irr(12)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(12)%mat(:,:,11) =  RESHAPE( (/-0.5-0.86603*j/), (/1, 1/) )
 Irr(12)%mat(:,:,12) =  RESHAPE( (/-0.5+0.86603*j/), (/1, 1/) )

 RETURN
  if (.FALSE.) write(std_out,*) j
 end subroutine ptg_C6h 
!!***

end module m_ptg_C6h
!!***
