!!****f* ABINIT/ptg_D6h
!!
!! NAME
!! ptg_D6h
!!
!! FUNCTION
!!
!! COPYRIGHT
!! Copyright (C) 2010-2020 ABINIT group (MG)
!! This file is distributed under the terms of the
!! GNU General Public License, see ~abinit/COPYING
!! or http://www.gnu.org/copyleft/gpl.txt .
!! For the initials of contributors, see ~abinit/doc/developers/contributors.txt .
!!
!! INPUTS
!!
!! OUTPUT
!!
!! PARENTS
!!      m_ptgroups
!!
!! CHILDREN
!!
!! SOURCE
!!
!********************************************************************************
! This include file has been automatically generated by the script ptg.py
! Do not edit! Change the script source instead.
!********************************************************************************

! Point group name  D6h (6/mmm)

#if defined HAVE_CONFIG_H
#include "config.h"
#endif

#include "abi_common.h"


module m_ptg_D6h
contains
!!**



 subroutine ptg_D6h (nsym,nclass,sym,class_ids,class_names,Irr)

#ifdef FC_INTEL
!DEC$ NOOPTIMIZE
#endif

 use defs_basis
 use m_abicore
 use m_defs_ptgroups,  only : irrep_t
 implicit none
!Arguments ------------------------------------
 integer,intent(out) :: nclass,nsym 
 !arrays
 integer,allocatable,intent(out) :: sym(:,:,:), class_ids(:,:)
 character(len=5),allocatable,intent(out) :: class_names(:)
 type(irrep_t),allocatable,intent(out) :: Irr(:)
 !Local variables-------------------------------
 complex(dpc) :: j=(0.0_dp,1.0_dp) 
 ! ********************************************************************************
! List of symmetries packed in classes
 nsym = 24
 ABI_MALLOC(sym, (3,3,nsym))
 sym(:,:,1) = RESHAPE( (/1, 0, 0, 0, 1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,2) = RESHAPE( (/0, 1, 0, -1, -1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,3) = RESHAPE( (/-1, -1, 0, 1, 0, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,4) = RESHAPE( (/-1, 0, 0, 0, -1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,5) = RESHAPE( (/0, -1, 0, 1, 1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,6) = RESHAPE( (/1, 1, 0, -1, 0, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,7) = RESHAPE( (/0, 1, 0, 1, 0, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,8) = RESHAPE( (/1, 0, 0, -1, -1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,9) = RESHAPE( (/-1, -1, 0, 0, 1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,10) = RESHAPE( (/0, -1, 0, -1, 0, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,11) = RESHAPE( (/-1, 0, 0, 1, 1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,12) = RESHAPE( (/1, 1, 0, 0, -1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,13) = RESHAPE( (/-1, 0, 0, 0, -1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,14) = RESHAPE( (/0, -1, 0, 1, 1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,15) = RESHAPE( (/1, 1, 0, -1, 0, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,16) = RESHAPE( (/1, 0, 0, 0, 1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,17) = RESHAPE( (/0, 1, 0, -1, -1, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,18) = RESHAPE( (/-1, -1, 0, 1, 0, 0, 0, 0, -1/) ,(/3,3/) )
 sym(:,:,19) = RESHAPE( (/0, -1, 0, -1, 0, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,20) = RESHAPE( (/-1, 0, 0, 1, 1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,21) = RESHAPE( (/1, 1, 0, 0, -1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,22) = RESHAPE( (/0, 1, 0, 1, 0, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,23) = RESHAPE( (/1, 0, 0, -1, -1, 0, 0, 0, 1/) ,(/3,3/) )
 sym(:,:,24) = RESHAPE( (/-1, -1, 0, 0, 1, 0, 0, 0, 1/) ,(/3,3/) )

! Number of classes and corresponding indeces
 nclass = 12
 ABI_MALLOC(class_ids, (2,nclass))
 class_ids(1,1) = 1
 class_ids(2,1) = 1
 class_ids(1,2) = 2
 class_ids(2,2) = 3
 class_ids(1,3) = 4
 class_ids(2,3) = 4
 class_ids(1,4) = 5
 class_ids(2,4) = 6
 class_ids(1,5) = 7
 class_ids(2,5) = 9
 class_ids(1,6) = 10
 class_ids(2,6) = 12
 class_ids(1,7) = 13
 class_ids(2,7) = 13
 class_ids(1,8) = 14
 class_ids(2,8) = 15
 class_ids(1,9) = 16
 class_ids(2,9) = 16
 class_ids(1,10) = 17
 class_ids(2,10) = 18
 class_ids(1,11) = 19
 class_ids(2,11) = 21
 class_ids(1,12) = 22
 class_ids(2,12) = 24

ABI_MALLOC(class_names,(12))
 class_names(1) = "1+" 
 class_names(2) = "3+" 
 class_names(3) = "2+" 
 class_names(4) = "6+" 
 class_names(5) = "2+" 
 class_names(6) = "2+" 
 class_names(7) = "-2-" 
 class_names(8) = "-6-" 
 class_names(9) = "-2+" 
 class_names(10) = "-6+" 
 class_names(11) = "-2+" 
 class_names(12) = "-2+" 

! List of irreducible representations.
 ABI_DT_MALLOC(Irr, (12))
 Irr(1)%name = "A1g"
 Irr(1)%dim = 1
 Irr(1)%nsym = 24
 ABI_MALLOC(Irr(1)%mat, (1,1,24))
 Irr(1)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,5) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,6) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,8) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,9) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,11) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,12) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,13) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,14) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,15) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,16) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,17) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,18) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,19) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,20) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,21) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,22) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,23) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(1)%mat(:,:,24) =  RESHAPE( (/1.0/), (/1, 1/) )

 Irr(2)%name = "A1u"
 Irr(2)%dim = 1
 Irr(2)%nsym = 24
 ABI_MALLOC(Irr(2)%mat, (1,1,24))
 Irr(2)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,5) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,6) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,8) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,9) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,11) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,12) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,13) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,14) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,15) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,16) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,17) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,18) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,19) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,20) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,21) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,22) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,23) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(2)%mat(:,:,24) =  RESHAPE( (/-1.0/), (/1, 1/) )

 Irr(3)%name = "A2g"
 Irr(3)%dim = 1
 Irr(3)%nsym = 24
 ABI_MALLOC(Irr(3)%mat, (1,1,24))
 Irr(3)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,5) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,6) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,8) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,9) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,11) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,12) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,13) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,14) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,15) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,16) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,17) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,18) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,19) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,20) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,21) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,22) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,23) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(3)%mat(:,:,24) =  RESHAPE( (/-1.0/), (/1, 1/) )

 Irr(4)%name = "A2u"
 Irr(4)%dim = 1
 Irr(4)%nsym = 24
 ABI_MALLOC(Irr(4)%mat, (1,1,24))
 Irr(4)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,4) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,5) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,6) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,8) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,9) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,11) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,12) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,13) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,14) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,15) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,16) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,17) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,18) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,19) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,20) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,21) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,22) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,23) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(4)%mat(:,:,24) =  RESHAPE( (/1.0/), (/1, 1/) )

 Irr(5)%name = "B1g"
 Irr(5)%dim = 1
 Irr(5)%nsym = 24
 ABI_MALLOC(Irr(5)%mat, (1,1,24))
 Irr(5)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,5) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,6) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,8) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,9) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,11) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,12) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,13) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,14) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,15) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,16) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,17) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,18) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,19) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,20) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,21) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,22) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,23) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(5)%mat(:,:,24) =  RESHAPE( (/-1.0/), (/1, 1/) )

 Irr(6)%name = "B1u"
 Irr(6)%dim = 1
 Irr(6)%nsym = 24
 ABI_MALLOC(Irr(6)%mat, (1,1,24))
 Irr(6)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,5) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,6) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,7) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,8) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,9) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,10) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,11) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,12) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,13) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,14) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,15) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,16) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,17) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,18) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,19) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,20) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,21) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,22) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,23) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(6)%mat(:,:,24) =  RESHAPE( (/1.0/), (/1, 1/) )

 Irr(7)%name = "B2g"
 Irr(7)%dim = 1
 Irr(7)%nsym = 24
 ABI_MALLOC(Irr(7)%mat, (1,1,24))
 Irr(7)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,5) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,6) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,8) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,9) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,11) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,12) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,13) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,14) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,15) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,16) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,17) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,18) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,19) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,20) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,21) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,22) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,23) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(7)%mat(:,:,24) =  RESHAPE( (/1.0/), (/1, 1/) )

 Irr(8)%name = "B2u"
 Irr(8)%dim = 1
 Irr(8)%nsym = 24
 ABI_MALLOC(Irr(8)%mat, (1,1,24))
 Irr(8)%mat(:,:,1) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,2) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,3) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,4) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,5) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,6) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,7) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,8) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,9) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,10) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,11) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,12) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,13) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,14) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,15) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,16) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,17) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,18) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,19) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,20) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,21) =  RESHAPE( (/1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,22) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,23) =  RESHAPE( (/-1.0/), (/1, 1/) )
 Irr(8)%mat(:,:,24) =  RESHAPE( (/-1.0/), (/1, 1/) )

 Irr(9)%name = "E2u"
 Irr(9)%dim = 2
 Irr(9)%nsym = 24
 ABI_MALLOC(Irr(9)%mat, (2,2,24))
 Irr(9)%mat(:,:,1) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(9)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,4) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(9)%mat(:,:,5) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,6) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,7) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(9)%mat(:,:,8) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(9)%mat(:,:,9) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(9)%mat(:,:,10) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(9)%mat(:,:,11) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(9)%mat(:,:,12) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(9)%mat(:,:,13) =  RESHAPE( (/-1.0, 0.0, 0.0, -1.0/), (/2, 2/) )
 Irr(9)%mat(:,:,14) =  RESHAPE( (/0.5-0.86603*j, 0*j, 0*j, 0.5+0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,15) =  RESHAPE( (/0.5+0.86603*j, 0*j, 0*j, 0.5-0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,16) =  RESHAPE( (/-1.0, 0.0, 0.0, -1.0/), (/2, 2/) )
 Irr(9)%mat(:,:,17) =  RESHAPE( (/0.5-0.86603*j, 0*j, 0*j, 0.5+0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,18) =  RESHAPE( (/0.5+0.86603*j, 0*j, 0*j, 0.5-0.86603*j/), (/2, 2/) )
 Irr(9)%mat(:,:,19) =  RESHAPE( (/0.0, -1.0, -1.0, 0.0/), (/2, 2/) )
 Irr(9)%mat(:,:,20) =  RESHAPE( (/0*j, 0.5-0.86603*j, 0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(9)%mat(:,:,21) =  RESHAPE( (/0*j, 0.5+0.86603*j, 0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(9)%mat(:,:,22) =  RESHAPE( (/0.0, -1.0, -1.0, 0.0/), (/2, 2/) )
 Irr(9)%mat(:,:,23) =  RESHAPE( (/0*j, 0.5-0.86603*j, 0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(9)%mat(:,:,24) =  RESHAPE( (/0*j, 0.5+0.86603*j, 0.5-0.86603*j, 0*j/), (/2, 2/) )

 Irr(10)%name = "E2g"
 Irr(10)%dim = 2
 Irr(10)%nsym = 24
 ABI_MALLOC(Irr(10)%mat, (2,2,24))
 Irr(10)%mat(:,:,1) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(10)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,4) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(10)%mat(:,:,5) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,6) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,7) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(10)%mat(:,:,8) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(10)%mat(:,:,9) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(10)%mat(:,:,10) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(10)%mat(:,:,11) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(10)%mat(:,:,12) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(10)%mat(:,:,13) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(10)%mat(:,:,14) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,15) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,16) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(10)%mat(:,:,17) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,18) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(10)%mat(:,:,19) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(10)%mat(:,:,20) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(10)%mat(:,:,21) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(10)%mat(:,:,22) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(10)%mat(:,:,23) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(10)%mat(:,:,24) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )

 Irr(11)%name = "E1u"
 Irr(11)%dim = 2
 Irr(11)%nsym = 24
 ABI_MALLOC(Irr(11)%mat, (2,2,24))
 Irr(11)%mat(:,:,1) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(11)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,4) =  RESHAPE( (/-1.0, 0.0, 0.0, -1.0/), (/2, 2/) )
 Irr(11)%mat(:,:,5) =  RESHAPE( (/0.5-0.86603*j, 0*j, 0*j, 0.5+0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,6) =  RESHAPE( (/0.5+0.86603*j, 0*j, 0*j, 0.5-0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,7) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(11)%mat(:,:,8) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(11)%mat(:,:,9) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(11)%mat(:,:,10) =  RESHAPE( (/0.0, -1.0, -1.0, 0.0/), (/2, 2/) )
 Irr(11)%mat(:,:,11) =  RESHAPE( (/0*j, 0.5-0.86603*j, 0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(11)%mat(:,:,12) =  RESHAPE( (/0*j, 0.5+0.86603*j, 0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(11)%mat(:,:,13) =  RESHAPE( (/-1.0, 0.0, 0.0, -1.0/), (/2, 2/) )
 Irr(11)%mat(:,:,14) =  RESHAPE( (/0.5-0.86603*j, 0*j, 0*j, 0.5+0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,15) =  RESHAPE( (/0.5+0.86603*j, 0*j, 0*j, 0.5-0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,16) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(11)%mat(:,:,17) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,18) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(11)%mat(:,:,19) =  RESHAPE( (/0.0, -1.0, -1.0, 0.0/), (/2, 2/) )
 Irr(11)%mat(:,:,20) =  RESHAPE( (/0*j, 0.5-0.86603*j, 0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(11)%mat(:,:,21) =  RESHAPE( (/0*j, 0.5+0.86603*j, 0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(11)%mat(:,:,22) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(11)%mat(:,:,23) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(11)%mat(:,:,24) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )

 Irr(12)%name = "E1g"
 Irr(12)%dim = 2
 Irr(12)%nsym = 24
 ABI_MALLOC(Irr(12)%mat, (2,2,24))
 Irr(12)%mat(:,:,1) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(12)%mat(:,:,2) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,3) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,4) =  RESHAPE( (/-1.0, 0.0, 0.0, -1.0/), (/2, 2/) )
 Irr(12)%mat(:,:,5) =  RESHAPE( (/0.5-0.86603*j, 0*j, 0*j, 0.5+0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,6) =  RESHAPE( (/0.5+0.86603*j, 0*j, 0*j, 0.5-0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,7) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(12)%mat(:,:,8) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(12)%mat(:,:,9) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(12)%mat(:,:,10) =  RESHAPE( (/0.0, -1.0, -1.0, 0.0/), (/2, 2/) )
 Irr(12)%mat(:,:,11) =  RESHAPE( (/0*j, 0.5-0.86603*j, 0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(12)%mat(:,:,12) =  RESHAPE( (/0*j, 0.5+0.86603*j, 0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(12)%mat(:,:,13) =  RESHAPE( (/1.0, 0.0, 0.0, 1.0/), (/2, 2/) )
 Irr(12)%mat(:,:,14) =  RESHAPE( (/-0.5+0.86603*j, 0*j, 0*j, -0.5-0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,15) =  RESHAPE( (/-0.5-0.86603*j, 0*j, 0*j, -0.5+0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,16) =  RESHAPE( (/-1.0, 0.0, 0.0, -1.0/), (/2, 2/) )
 Irr(12)%mat(:,:,17) =  RESHAPE( (/0.5-0.86603*j, 0*j, 0*j, 0.5+0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,18) =  RESHAPE( (/0.5+0.86603*j, 0*j, 0*j, 0.5-0.86603*j/), (/2, 2/) )
 Irr(12)%mat(:,:,19) =  RESHAPE( (/0.0, 1.0, 1.0, 0.0/), (/2, 2/) )
 Irr(12)%mat(:,:,20) =  RESHAPE( (/0*j, -0.5+0.86603*j, -0.5-0.86603*j, 0*j/), (/2, 2/) )
 Irr(12)%mat(:,:,21) =  RESHAPE( (/0*j, -0.5-0.86603*j, -0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(12)%mat(:,:,22) =  RESHAPE( (/0.0, -1.0, -1.0, 0.0/), (/2, 2/) )
 Irr(12)%mat(:,:,23) =  RESHAPE( (/0*j, 0.5-0.86603*j, 0.5+0.86603*j, 0*j/), (/2, 2/) )
 Irr(12)%mat(:,:,24) =  RESHAPE( (/0*j, 0.5+0.86603*j, 0.5-0.86603*j, 0*j/), (/2, 2/) )

 RETURN
  if (.FALSE.) write(std_out,*) j
 end subroutine ptg_D6h 
!!***

end module m_ptg_D6h
!!***
