# Generated by make-macros-patches on 2019/03/04 18:31:29 +0000

#
# Check whether fallbacks have patches
#

#
# IMPORTANT NOTE
#
# This file has been automatically generated by the make-macros-patches
# script. If you try to edit it, your changes will systematically be
# overwritten.
#



# AFB_PATCHES_SETUP()
# -------------------
#
# Tells the user which packages have patches.
#
AC_DEFUN([AFB_PATCHES_SETUP],[
]) # AFB_PATCHES_SETUP
