#!/bin/bash
# Copyright (C) 1998-2020 ABINIT group (XG).
# 
# Change the reference files to allow the ngfft to be present in the diff

for file in "$@"
do
 echo "working on $file"
 rm -f tmp.file
 sed -e 's&getcut:&getcut &' $file > tmp.file
 echo "changes done "
 # put the modified file at the correct place
 rm -f $file 
 mv tmp.file $file
 echo "file $file written "
done
