The build system of Abinit could not find any program to
download the fallback source tarballs. You might thus not be
able to build some fallbacks.

There are two ways to address this issue:

  \\* either download all fallbacks manually and store them in
    a directory called "~/.abinit/tarballs/"; or

  \\* install the "wget" and/or "curl" utilities, using your
    favorite package management software or compiling them from
    source.

The wget utility can be downloaded from:

  http://www.gnu.org/software/wget/

The curl utility can be downloaded from:

  http://curl.haxx.se/download.html

For more info, please consult the Abinit forums at
https://forum.abinit.org/.
