The ETSF_IO library is not used anymore:
it has been replaced by an internal NetCDF implementation
of the ETSF File Format Specification in Abinit.
The support of the ETSF_IO library will soon end.

IMPORTANT: Do not be mistaken!
The ETSF File Format Specification is used for most
ABINIT NetCDF files and will continue to be so
in the foreseen future.

Please contact Matteo Giantomassi for any question about the
new implementation of the reading and writing of the
ETSF formatted files.
