#exclude: ^(docs|tests/files|tasks.py)

ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: ['--maxkb=15000']  # 1000 KB = 1 MB
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: check-build-config
        name: Run check-build-config
        entry: python abichecks/scripts/check-build-config.py
        language: python
      - id: run-check-config-h
        name: Run run-check-config-h
        entry: python abichecks/scripts/check-config-h.py
        language: python
      - id: run-check-ascii
        name: Run run-check_ascii
        entry: python abichecks/scripts/check_ascii.py
        language: python
      #- id: run-warningschk
      #  name: Run run-warningschk
      #  entry: python abichecks/scripts/warningschk.py
      #  language: python
      #- id: check-libpaw
      #  name: Run check-libpaw
      #  entry: python abichecks/scripts/check-libpaw.py
      #  language: python
      - id: check-forbidden
        name: Run check-forbidden
        entry: python abichecks/scripts/check_forbidden.py
        language: python
      - id: check-binaries-conf
        name: Run check-binaries-conf
        entry: python abichecks/scripts/check-binaries-conf.py
        language: python
      - id: check-cpp-options
        name: Run check-cpp-options
        entry: python abichecks/scripts/check-cpp-options.py
        language: python
      - id: check-inlined-macros
        name: run check-inlined-macros
        entry: python abichecks/scripts/check_inlined_macros.py
        language: python
      - id: check-unprotected-omp-target
        name: run check-unprotected-omp-target.py
        entry: python abichecks/scripts/check-unprotected-omp-target.py
        language: python
