#!/bin/sh

# Init
my_name=`basename "${0}"`

# Stop at first error
set -e

# Check arguments
if test "${#}" -lt "2"; then
  echo "Usage: ${my_name} scrdir builddir"
  exit 0
fi

# Shrink long lines in m_build_info
${1}/config/scripts/cut-long-lines \
  <"${2}/shared/common/src/14_hidewrite/m_build_info.F90" \
  >"${2}/shared/common/src/14_hidewrite/m_build_info.F90.tmp-${$}"
mv "${2}/shared/common/src/14_hidewrite/m_build_info.F90.tmp-${$}" \
  "${2}/shared/common/src/14_hidewrite/m_build_info.F90"
