#
# Config file for the Abinit documentation
#

# Permitted options:
#
#   * type = (data|source)
#

# Note: unlisted directories will be ignored.

[DEFAULT]
type = data

[build]
type = data

[developers]
ignore = strainpert.pdf

[guide]
type = source
docs =
  aimhelp
  conducti_manual
  conductivity_paw_manu
  elphon_manual
  linear_optics_paw
  xtalinput
aimhelp = tex aimhelp.tex
conducti_manual = tex conducti_manual.tex
conductivity_paw_manu = tex conductivity_paw_manu.tex
elphon_manual = tex elphon_manual.tex
linear_optics_paw = tex linear_optics_paw.tex
xtalinput = tex xtalinput.tex

[help_make]

[macroave]
type = source
docs = macroave
macroave = tex

[maintainers]

[presentation]

[theory]
type = source
extra = ELF KDEN MGGA elasticity-oganov.odt elasticity-oganov.pdf response.pdf gwa.pdf
docs =
  fixd_theory
  gwa
  vanderbilt-anaddb-notes
fixd_theory = tex fixd_theory.tex
gwa = tex gwa.tex
vanderbilt-anaddb-notes = tex vanderbilt-anaddb-notes.tex response.pdf

[tutorial]

[faq]

[variables]
