/* This file has been automatically generated, do not modify. */
#ifndef AB7_INVARS_C_H
#define AB7_INVARS_C_H

static Ab7InvarsTypes ab7_invars_types[] = {
           _INT_SCALAR    ,  /* iomode          */
           _INT_SCALAR    ,  /* accuracy        */
           _INT_SCALAR    ,  /* adpimd          */
           _INT_SCALAR    ,  /* autoparal       */
           _INT_SCALAR    ,  /* auxc_ixc        */
           _INT_SCALAR    ,  /* awtr            */
           _INT_SCALAR    ,  /* bandpp          */
           _INT_SCALAR    ,  /* bdeigrf         */
           _INT_SCALAR    ,  /* berryopt        */
           _INT_SCALAR    ,  /* berrysav        */
           _INT_SCALAR    ,  /* berrystep       */
           _INT_SCALAR    ,  /* brvltt          */
           _INT_SCALAR    ,  /* bs_nstates      */
           _INT_SCALAR    ,  /* bs_hayd_term    */
           _INT_SCALAR    ,  /* builtintest     */
           _INT_SCALAR    ,  /* cd_full_grid    */
           _INT_SCALAR    ,  /* cd_frqim_method */
           _INT_SCALAR    ,  /* cd_customnimfrqs */
           _INT_SCALAR    ,  /* chkdilatmx      */
           _INT_SCALAR    ,  /* chkexit         */
           _INT_SCALAR    ,  /* chkprim         */
           _INT_SCALAR    ,  /* chksymbreak     */
           _INT_SCALAR    ,  /* cineb_start     */
           _INT_SCALAR    ,  /* delayperm       */
           _INT_SCALAR    ,  /* densfor_pred    */
           _INT_SCALAR    ,  /* diismemory      */
           _INT_SCALAR    ,  /* dmatpuopt       */
           _INT_SCALAR    ,  /* dmatudiag       */
           _INT_SCALAR    ,  /* dmft_dc         */
           _INT_SCALAR    ,  /* dmft_entropy    */
           _INT_SCALAR    ,  /* dmft_iter       */
           _INT_SCALAR    ,  /* dmft_nlambda    */
           _INT_SCALAR    ,  /* dmft_nwli       */
           _INT_SCALAR    ,  /* dmft_nwlo       */
           _INT_SCALAR    ,  /* dmft_rslf       */
           _INT_SCALAR    ,  /* dmft_read_occnd */
           _INT_SCALAR    ,  /* dmft_solv       */
           _INT_SCALAR    ,  /* dmft_t2g        */
           _INT_SCALAR    ,  /* dmftbandi       */
           _INT_SCALAR    ,  /* dmftbandf       */
           _INT_SCALAR    ,  /* dmftcheck       */
           _INT_SCALAR    ,  /* dmftctqmc_basis */
           _INT_SCALAR    ,  /* dmftctqmc_check */
           _INT_SCALAR    ,  /* dmftctqmc_correl */
           _INT_SCALAR    ,  /* dmftctqmc_gmove */
           _INT_SCALAR    ,  /* dmftctqmc_grnns */
           _INT_SCALAR    ,  /* dmftctqmc_meas  */
           _INT_SCALAR    ,  /* dmftctqmc_mov   */
           _INT_SCALAR    ,  /* dmftctqmc_mrka  */
           _INT_SCALAR    ,  /* dmftctqmc_order */
           _INT_SCALAR    ,  /* dmftctqmc_triqs_nleg */
           _INT_SCALAR    ,  /* dmftqmc_l       */
           _INT_SCALAR    ,  /* dmftqmc_seed    */
           _INT_SCALAR    ,  /* dmftqmc_therm   */
           _INT_SCALAR    ,  /* d3e_pert1_elfd  */
           _INT_SCALAR    ,  /* d3e_pert1_phon  */
           _INT_SCALAR    ,  /* d3e_pert2_elfd  */
           _INT_SCALAR    ,  /* d3e_pert2_phon  */
           _INT_SCALAR    ,  /* d3e_pert3_elfd  */
           _INT_SCALAR    ,  /* d3e_pert3_phon  */
           _INT_SCALAR    ,  /* efmas           */
           _INT_SCALAR    ,  /* efmas_calc_dirs */
           _INT_SCALAR    ,  /* efmas_deg       */
           _INT_SCALAR    ,  /* efmas_dim       */
           _INT_SCALAR    ,  /* efmas_n_dirs    */
           _INT_SCALAR    ,  /* efmas_ntheta    */
           _INT_SCALAR    ,  /* enunit          */
           _INT_SCALAR    ,  /* eph_task        */
           _INT_SCALAR    ,  /* exchn2n3d       */
           _INT_SCALAR    ,  /* extrapwf        */
           _INT_SCALAR    ,  /* fftgw           */
           _INT_SCALAR    ,  /* fockoptmix      */
           _INT_SCALAR    ,  /* frzfermi        */
           _INT_SCALAR    ,  /* ga_algor        */
           _INT_SCALAR    ,  /* ga_fitness      */
           _INT_SCALAR    ,  /* ga_n_rules      */
           _INT_SCALAR    ,  /* getcell         */
           _INT_SCALAR    ,  /* getddb          */
           _INT_SCALAR    ,  /* getddk          */
           _INT_SCALAR    ,  /* getdelfd        */
           _INT_SCALAR    ,  /* getdkdk         */
           _INT_SCALAR    ,  /* getdkde         */
           _INT_SCALAR    ,  /* getden          */
           _INT_SCALAR    ,  /* getefmas        */
           _INT_SCALAR    ,  /* getgam_eig2nkq  */
           _INT_SCALAR    ,  /* getocc          */
           _INT_SCALAR    ,  /* getpawden       */
           _INT_SCALAR    ,  /* getqps          */
           _INT_SCALAR    ,  /* getscr          */
           _INT_SCALAR    ,  /* getsuscep       */
           _INT_SCALAR    ,  /* getvel          */
           _INT_SCALAR    ,  /* getwfk          */
           _INT_SCALAR    ,  /* getwfkfine      */
           _INT_SCALAR    ,  /* getwfq          */
           _INT_SCALAR    ,  /* getxcart        */
           _INT_SCALAR    ,  /* getxred         */
           _INT_SCALAR    ,  /* get1den         */
           _INT_SCALAR    ,  /* get1wf          */
           _INT_SCALAR    ,  /* getbseig        */
           _INT_SCALAR    ,  /* getbsreso       */
           _INT_SCALAR    ,  /* getbscoup       */
           _INT_SCALAR    ,  /* gethaydock      */
           _INT_SCALAR    ,  /* goprecon        */
           _INT_SCALAR    ,  /* gwcalctyp       */
           _INT_SCALAR    ,  /* gwcomp          */
           _INT_SCALAR    ,  /* gwgamma         */
           _INT_SCALAR    ,  /* gwrpacorr       */
           _INT_SCALAR    ,  /* gw_customnfreqsp */
           _INT_SCALAR    ,  /* gw_invalid_freq */
           _INT_SCALAR    ,  /* gw_qprange      */
           _INT_SCALAR    ,  /* gw_nqlwl        */
           _INT_SCALAR    ,  /* gw_nstep        */
           _INT_SCALAR    ,  /* gw_sigxcore     */
           _INT_SCALAR    ,  /* gwls_stern_kmax */
           _INT_SCALAR    ,  /* gwls_npt_gauss_quad */
           _INT_SCALAR    ,  /* gwls_diel_model */
           _INT_SCALAR    ,  /* gwls_print_debug */
           _INT_SCALAR    ,  /* gwls_nseeds     */
           _INT_SCALAR    ,  /* gwls_n_proj_freq */
           _INT_SCALAR    ,  /* gwls_kmax_complement */
           _INT_SCALAR    ,  /* gwls_kmax_poles */
           _INT_SCALAR    ,  /* gwls_kmax_analytic */
           _INT_SCALAR    ,  /* gwls_kmax_numeric */
           _INT_SCALAR    ,  /* gwls_band_index */
           _INT_SCALAR    ,  /* gwls_exchange   */
           _INT_SCALAR    ,  /* gwls_correlation */
           _INT_SCALAR    ,  /* gwls_first_seed */
           _INT_SCALAR    ,  /* gwls_recycle    */
           _INT_SCALAR    ,  /* gw_frqim_inzgrid */
           _INT_SCALAR    ,  /* gw_frqre_inzgrid */
           _INT_SCALAR    ,  /* gw_frqre_tangrid */
           _INT_SCALAR    ,  /* gw_sctype       */
           _INT_SCALAR    ,  /* gwmem           */
           _INT_SCALAR    ,  /* gwpara          */
           _INT_SCALAR    ,  /* hmcsst          */
           _INT_SCALAR    ,  /* hmctt           */
           _INT_SCALAR    ,  /* iboxcut         */
           _INT_SCALAR    ,  /* icoulomb        */
           _INT_SCALAR    ,  /* icutcoul        */
           _INT_SCALAR    ,  /* ieig2rf         */
           _INT_SCALAR    ,  /* imgmov          */
           _INT_SCALAR    ,  /* imgwfstor       */
           _INT_SCALAR    ,  /* inclvkb         */
           _INT_SCALAR    ,  /* intxc           */
           _INT_SCALAR    ,  /* ionmov          */
           _INT_SCALAR    ,  /* iprcel          */
           _INT_SCALAR    ,  /* iprcfc          */
           _INT_SCALAR    ,  /* irandom         */
           _INT_SCALAR    ,  /* irdddb          */
           _INT_SCALAR    ,  /* irdddk          */
           _INT_SCALAR    ,  /* irdden          */
           _INT_SCALAR    ,  /* irdefmas        */
           _INT_SCALAR    ,  /* irdhaydock      */
           _INT_SCALAR    ,  /* irdpawden       */
           _INT_SCALAR    ,  /* irdqps          */
           _INT_SCALAR    ,  /* irdscr          */
           _INT_SCALAR    ,  /* irdsuscep       */
           _INT_SCALAR    ,  /* irdvdw          */
           _INT_SCALAR    ,  /* irdwfk          */
           _INT_SCALAR    ,  /* irdwfkfine      */
           _INT_SCALAR    ,  /* irdwfq          */
           _INT_SCALAR    ,  /* ird1den         */
           _INT_SCALAR    ,  /* ird1wf          */
           _INT_SCALAR    ,  /* irdbseig        */
           _INT_SCALAR    ,  /* irdbsreso       */
           _INT_SCALAR    ,  /* irdbscoup       */
           _INT_SCALAR    ,  /* iscf            */
           _INT_SCALAR    ,  /* isecur          */
           _INT_SCALAR    ,  /* istatimg        */
           _INT_SCALAR    ,  /* istatr          */
           _INT_SCALAR    ,  /* istatshft       */
           _INT_SCALAR    ,  /* ixc             */
           _INT_SCALAR    ,  /* ixc_sigma       */
           _INT_SCALAR    ,  /* ixcpositron     */
           _INT_SCALAR    ,  /* ixcrot          */
           _INT_SCALAR    ,  /* jdtset          */
           _INT_SCALAR    ,  /* jellslab        */
           _INT_SCALAR    ,  /* kptopt          */
           _INT_SCALAR    ,  /* kssform         */
           _INT_SCALAR    ,  /* localrdwf       */
           _INT_SCALAR    ,  /* lotf_classic    */
           _INT_SCALAR    ,  /* lotf_nitex      */
           _INT_SCALAR    ,  /* lotf_nneigx     */
           _INT_SCALAR    ,  /* lotf_version    */
           _INT_SCALAR    ,  /* magconon        */
           _INT_SCALAR    ,  /* maxnsym         */
           _INT_SCALAR    ,  /* max_ncpus       */
           _INT_SCALAR    ,  /* mband           */
           _INT_SCALAR    ,  /* mep_solver      */
           _INT_SCALAR    ,  /* mem_test        */
           _INT_SCALAR    ,  /* mffmem          */
           _INT_SCALAR    ,  /* mgfft           */
           _INT_SCALAR    ,  /* mgfftdg         */
           _INT_SCALAR    ,  /* mkmem           */
           _INT_SCALAR    ,  /* mkqmem          */
           _INT_SCALAR    ,  /* mk1mem          */
           _INT_SCALAR    ,  /* nnos            */
           _INT_SCALAR    ,  /* mpw             */
           _INT_SCALAR    ,  /* mqgrid          */
           _INT_SCALAR    ,  /* mqgriddg        */
           _INT_SCALAR    ,  /* natom           */
           _INT_SCALAR    ,  /* natpawu         */
           _INT_SCALAR    ,  /* natrd           */
           _INT_SCALAR    ,  /* natsph          */
           _INT_SCALAR    ,  /* natsph_extra    */
           _INT_SCALAR    ,  /* natvshift       */
           _INT_SCALAR    ,  /* nbandhf         */
           _INT_SCALAR    ,  /* nbandkss        */
           _INT_SCALAR    ,  /* nbdblock        */
           _INT_SCALAR    ,  /* nbdbuf          */
           _INT_SCALAR    ,  /* nberry          */
           _INT_SCALAR    ,  /* nc_xccc_gspace  */
           _INT_SCALAR    ,  /* nconeq          */
           _INT_SCALAR    ,  /* nctime          */
           _INT_SCALAR    ,  /* ndtset          */
           _INT_SCALAR    ,  /* ndynimage       */
           _INT_SCALAR    ,  /* neb_algo        */
           _INT_SCALAR    ,  /* nfft            */
           _INT_SCALAR    ,  /* nfftdg          */
           _INT_SCALAR    ,  /* nfreqim         */
           _INT_SCALAR    ,  /* nfreqre         */
           _INT_SCALAR    ,  /* nfreqsp         */
           _INT_SCALAR    ,  /* nimage          */
           _INT_SCALAR    ,  /* nkpt            */
           _INT_SCALAR    ,  /* nkptgw          */
           _INT_SCALAR    ,  /* nkpthf          */
           _INT_SCALAR    ,  /* nline           */
           _INT_SCALAR    ,  /* nnsclo          */
           _INT_SCALAR    ,  /* nnsclohf        */
           _INT_SCALAR    ,  /* nomegasf        */
           _INT_SCALAR    ,  /* nomegasi        */
           _INT_SCALAR    ,  /* nomegasrd       */
           _INT_SCALAR    ,  /* nonlinear_info  */
           _INT_SCALAR    ,  /* npband          */
           _INT_SCALAR    ,  /* npfft           */
           _INT_SCALAR    ,  /* nphf            */
           _INT_SCALAR    ,  /* npimage         */
           _INT_SCALAR    ,  /* npkpt           */
           _INT_SCALAR    ,  /* nppert          */
           _INT_SCALAR    ,  /* npspinor        */
           _INT_SCALAR    ,  /* npsp            */
           _INT_SCALAR    ,  /* npspalch        */
           _INT_SCALAR    ,  /* npulayit        */
           _INT_SCALAR    ,  /* npvel           */
           _INT_SCALAR    ,  /* npweps          */
           _INT_SCALAR    ,  /* npwkss          */
           _INT_SCALAR    ,  /* npwsigx         */
           _INT_SCALAR    ,  /* npwwfn          */
           _INT_SCALAR    ,  /* np_slk          */
           _INT_SCALAR    ,  /* nqpt            */
           _INT_SCALAR    ,  /* nqptdm          */
           _INT_SCALAR    ,  /* nscforder       */
           _INT_SCALAR    ,  /* nshiftk         */
           _INT_SCALAR    ,  /* nshiftk_orig    */
           _INT_SCALAR    ,  /* nspden          */
           _INT_SCALAR    ,  /* nspinor         */
           _INT_SCALAR    ,  /* nsppol          */
           _INT_SCALAR    ,  /* nstep           */
           _INT_SCALAR    ,  /* nsym            */
           _INT_SCALAR    ,  /* ntime           */
           _INT_SCALAR    ,  /* ntimimage       */
           _INT_SCALAR    ,  /* ntypalch        */
           _INT_SCALAR    ,  /* ntypat          */
           _INT_SCALAR    ,  /* ntyppure        */
           _INT_SCALAR    ,  /* nwfshist        */
           _INT_SCALAR    ,  /* nzchempot       */
           _INT_SCALAR    ,  /* occopt          */
           _INT_SCALAR    ,  /* optcell         */
           _INT_SCALAR    ,  /* optdriver       */
           _INT_SCALAR    ,  /* optforces       */
           _INT_SCALAR    ,  /* optnlxccc       */
           _INT_SCALAR    ,  /* optstress       */
           _INT_SCALAR    ,  /* orbmag          */
           _INT_SCALAR    ,  /* ortalg          */
           _INT_SCALAR    ,  /* paral_atom      */
           _INT_SCALAR    ,  /* paral_kgb       */
           _INT_SCALAR    ,  /* paral_rf        */
           _INT_SCALAR    ,  /* pawcpxocc       */
           _INT_SCALAR    ,  /* pawcross        */
           _INT_SCALAR    ,  /* pawfatbnd       */
           _INT_SCALAR    ,  /* pawlcutd        */
           _INT_SCALAR    ,  /* pawlmix         */
           _INT_SCALAR    ,  /* pawmixdg        */
           _INT_SCALAR    ,  /* pawnhatxc       */
           _INT_SCALAR    ,  /* pawnphi         */
           _INT_SCALAR    ,  /* pawntheta       */
           _INT_SCALAR    ,  /* pawnzlm         */
           _INT_SCALAR    ,  /* pawoptmix       */
           _INT_SCALAR    ,  /* pawoptosc       */
           _INT_SCALAR    ,  /* pawprtdos       */
           _INT_SCALAR    ,  /* pawprtvol       */
           _INT_SCALAR    ,  /* pawprtwf        */
           _INT_SCALAR    ,  /* pawprt_k        */
           _INT_SCALAR    ,  /* pawprt_b        */
           _INT_SCALAR    ,  /* pawspnorb       */
           _INT_SCALAR    ,  /* pawstgylm       */
           _INT_SCALAR    ,  /* pawsushat       */
           _INT_SCALAR    ,  /* pawusecp        */
           _INT_SCALAR    ,  /* macro_uj        */
           _INT_SCALAR    ,  /* pawujat         */
           _INT_SCALAR    ,  /* pawxcdev        */
           _INT_SCALAR    ,  /* pimd_constraint */
           _INT_SCALAR    ,  /* pitransform     */
           _INT_SCALAR    ,  /* plowan_bandi    */
           _INT_SCALAR    ,  /* plowan_bandf    */
           _INT_SCALAR    ,  /* plowan_compute  */
           _INT_SCALAR    ,  /* plowan_natom    */
           _INT_SCALAR    ,  /* plowan_nt       */
           _INT_SCALAR    ,  /* plowan_realspace */
           _INT_SCALAR    ,  /* posdoppler      */
           _INT_SCALAR    ,  /* positron        */
           _INT_SCALAR    ,  /* posnstep        */
           _INT_SCALAR    ,  /* ppmodel         */
           _INT_SCALAR    ,  /* prepanl         */
           _INT_SCALAR    ,  /* prepgkk         */
           _INT_SCALAR    ,  /* prtbbb          */
           _INT_SCALAR    ,  /* prtbltztrp      */
           _INT_SCALAR    ,  /* prtcif          */
           _INT_SCALAR    ,  /* prtden          */
           _INT_SCALAR    ,  /* prtdensph       */
           _INT_SCALAR    ,  /* prtdipole       */
           _INT_SCALAR    ,  /* prtdos          */
           _INT_SCALAR    ,  /* prtdosm         */
           _INT_SCALAR    ,  /* prtebands       */
           _INT_SCALAR    ,  /* prtefg          */
           _INT_SCALAR    ,  /* prtefmas        */
           _INT_SCALAR    ,  /* prteig          */
           _INT_SCALAR    ,  /* prtelf          */
           _INT_SCALAR    ,  /* prtfc           */
           _INT_SCALAR    ,  /* prtfull1wf      */
           _INT_SCALAR    ,  /* prtfsurf        */
           _INT_SCALAR    ,  /* prtgsr          */
           _INT_SCALAR    ,  /* prtgden         */
           _INT_SCALAR    ,  /* prtgeo          */
           _INT_SCALAR    ,  /* prtgkk          */
           _INT_SCALAR    ,  /* prtkden         */
           _INT_SCALAR    ,  /* prtkpt          */
           _INT_SCALAR    ,  /* prtlden         */
           _INT_SCALAR    ,  /* prtnabla        */
           _INT_SCALAR    ,  /* prtnest         */
           _INT_SCALAR    ,  /* prtpmp          */
           _INT_SCALAR    ,  /* prtposcar       */
           _INT_SCALAR    ,  /* prtphdos        */
           _INT_SCALAR    ,  /* prtphbands      */
           _INT_SCALAR    ,  /* prtphsurf       */
           _INT_SCALAR    ,  /* prtpot          */
           _INT_SCALAR    ,  /* prtpsps         */
           _INT_SCALAR    ,  /* prtspcur        */
           _INT_SCALAR    ,  /* prtstm          */
           _INT_SCALAR    ,  /* prtsuscep       */
           _INT_SCALAR    ,  /* prtvclmb        */
           _INT_SCALAR    ,  /* prtvdw          */
           _INT_SCALAR    ,  /* prtvha          */
           _INT_SCALAR    ,  /* prtvhxc         */
           _INT_SCALAR    ,  /* prtkbff         */
           _INT_SCALAR    ,  /* prtvol          */
           _INT_SCALAR    ,  /* prtvolimg       */
           _INT_SCALAR    ,  /* prtvpsp         */
           _INT_SCALAR    ,  /* prtvxc          */
           _INT_SCALAR    ,  /* prtwant         */
           _INT_SCALAR    ,  /* prtwf           */
           _INT_SCALAR    ,  /* prtwf_full      */
           _INT_SCALAR    ,  /* prtxml          */
           _INT_SCALAR    ,  /* prt1dm          */
           _INT_SCALAR    ,  /* ptgroupma       */
           _INT_SCALAR    ,  /* qptopt          */
           _INT_SCALAR    ,  /* random_atpos    */
           _INT_SCALAR    ,  /* recgratio       */
           _INT_SCALAR    ,  /* recnpath        */
           _INT_SCALAR    ,  /* recnrec         */
           _INT_SCALAR    ,  /* recptrott       */
           _INT_SCALAR    ,  /* rectesteg       */
           _INT_SCALAR    ,  /* restartxf       */
           _INT_SCALAR    ,  /* rfasr           */
           _INT_SCALAR    ,  /* rfddk           */
           _INT_SCALAR    ,  /* rfelfd          */
           _INT_SCALAR    ,  /* rfmagn          */
           _INT_SCALAR    ,  /* rfmeth          */
           _INT_SCALAR    ,  /* rfphon          */
           _INT_SCALAR    ,  /* rfstrs          */
           _INT_SCALAR    ,  /* rfuser          */
           _INT_SCALAR    ,  /* rf2_dkdk        */
           _INT_SCALAR    ,  /* rf2_dkde        */
           _INT_SCALAR    ,  /* signperm        */
           _INT_SCALAR    ,  /* slk_rankpp      */
           _INT_SCALAR    ,  /* smdelta         */
           _INT_SCALAR    ,  /* spgaxor         */
           _INT_SCALAR    ,  /* spgorig         */
           _INT_SCALAR    ,  /* spgroup         */
           _INT_SCALAR    ,  /* spmeth          */
           _INT_SCALAR    ,  /* string_algo     */
           _INT_SCALAR    ,  /* symmorphi       */
           _INT_SCALAR    ,  /* symchi          */
           _INT_SCALAR    ,  /* symsigma        */
           _INT_SCALAR    ,  /* td_mexcit       */
           _INT_SCALAR    ,  /* tfkinfunc       */
           _INT_SCALAR    ,  /* tim1rev         */
           _INT_SCALAR    ,  /* timopt          */
           _INT_SCALAR    ,  /* tl_nprccg       */
           _INT_SCALAR    ,  /* ucrpa           */
           _INT_SCALAR    ,  /* use_gpu_cuda    */
           _INT_SCALAR    ,  /* usedmatpu       */
           _INT_SCALAR    ,  /* usedmft         */
           _INT_SCALAR    ,  /* useexexch       */
           _INT_SCALAR    ,  /* usefock         */
           _INT_SCALAR    ,  /* usekden         */
           _INT_SCALAR    ,  /* use_gemm_nonlop */
           _INT_SCALAR    ,  /* use_nonscf_gkk  */
           _INT_SCALAR    ,  /* usepaw          */
           _INT_SCALAR    ,  /* usepawu         */
           _INT_SCALAR    ,  /* usepead         */
           _INT_SCALAR    ,  /* usepotzero      */
           _INT_SCALAR    ,  /* userec          */
           _INT_SCALAR    ,  /* useria          */
           _INT_SCALAR    ,  /* userib          */
           _INT_SCALAR    ,  /* useric          */
           _INT_SCALAR    ,  /* userid          */
           _INT_SCALAR    ,  /* userie          */
           _INT_SCALAR    ,  /* usewvl          */
           _INT_SCALAR    ,  /* usexcnhat_orig  */
           _INT_SCALAR    ,  /* useylm          */
           _INT_SCALAR    ,  /* use_slk         */
           _INT_SCALAR    ,  /* vacnum          */
           _INT_SCALAR    ,  /* vdw_nfrag       */
           _INT_SCALAR    ,  /* vdw_df_ndpts    */
           _INT_SCALAR    ,  /* vdw_df_ngpts    */
           _INT_SCALAR    ,  /* vdw_df_nqpts    */
           _INT_SCALAR    ,  /* vdw_df_nrpts    */
           _INT_SCALAR    ,  /* vdw_df_nsmooth  */
           _INT_SCALAR    ,  /* vdw_df_tweaks   */
           _INT_SCALAR    ,  /* vdw_xc          */
           _INT_SCALAR    ,  /* wfoptalg        */
           _INT_SCALAR    ,  /* wfk_task        */
           _INT_SCALAR    ,  /* wvl_bigdft_comp */
           _INT_SCALAR    ,  /* wvl_nprccg      */
           _INT_SCALAR    ,  /* w90iniprj       */
           _INT_SCALAR    ,  /* w90prtunk       */
           _INT_SCALAR    ,  /* xclevel         */
           _INT_ARRAY     ,  /* bdberry         */
           _INT_ARRAY     ,  /* bravais         */
           _INT_ARRAY     ,  /* cd_subset_freq  */
           _INT_ARRAY     ,  /* d3e_pert1_atpol */
           _INT_ARRAY     ,  /* d3e_pert1_dir   */
           _INT_ARRAY     ,  /* d3e_pert2_atpol */
           _INT_ARRAY     ,  /* d3e_pert2_dir   */
           _INT_ARRAY     ,  /* d3e_pert3_atpol */
           _INT_ARRAY     ,  /* d3e_pert3_dir   */
           _INT_ARRAY     ,  /* fockdownsampling */
           _INT_ARRAY     ,  /* jfielddir       */
           _INT_ARRAY     ,  /* kptrlatt        */
           _INT_ARRAY     ,  /* kptrlatt_orig   */
           _INT_ARRAY     ,  /* qptrlatt        */
           _INT_ARRAY     ,  /* ga_rules        */
           _INT_ARRAY     ,  /* gpu_devices     */
           _INT_ARRAY     ,  /* ngfft           */
           _INT_ARRAY     ,  /* ngfftdg         */
           _INT_ARRAY     ,  /* nloalg          */
           _INT_ARRAY     ,  /* ngkpt           */
           _INT_ARRAY     ,  /* qprtrb          */
           _INT_ARRAY     ,  /* rfatpol         */
           _INT_ARRAY     ,  /* rfdir           */
           _INT_ARRAY     ,  /* rf2_pert1_dir   */
           _INT_ARRAY     ,  /* rf2_pert2_dir   */
           _INT_ARRAY     ,  /* supercell_latt  */
           _INT_ARRAY     ,  /* ucrpa_bands     */
           _INT_ARRAY     ,  /* vdw_supercell   */
           _INT_ARRAY     ,  /* vdw_typfrag     */
           _INT_ARRAY     ,  /* wvl_ngauss      */
           _INT_ARRAY     ,  /* algalch         */
           _INT_ARRAY     ,  /* bdgw            */
           _INT_ARRAY     ,  /* dynimage        */
           _INT_ARRAY     ,  /* efmas_bands     */
           _INT_ARRAY     ,  /* iatfix          */
           _INT_ARRAY     ,  /* iatsph          */
           _INT_ARRAY     ,  /* istwfk          */
           _INT_ARRAY     ,  /* kberry          */
           _INT_ARRAY     ,  /* lexexch         */
           _INT_ARRAY     ,  /* ldaminushalf    */
           _INT_ARRAY     ,  /* lpawu           */
           _INT_ARRAY     ,  /* nband           */
           _INT_ARRAY     ,  /* plowan_iatom    */
           _INT_ARRAY     ,  /* plowan_it       */
           _INT_ARRAY     ,  /* plowan_lcalc    */
           _INT_ARRAY     ,  /* plowan_nbl      */
           _INT_ARRAY     ,  /* plowan_projcalc */
           _INT_ARRAY     ,  /* prtatlist       */
           _INT_ARRAY     ,  /* so_psp          */
           _INT_ARRAY     ,  /* symafm          */
           _INT_ARRAY     ,  /* symrel          */
           _INT_ARRAY     ,  /* typat           */
           _DOUBLE_SCALAR ,  /* adpimd_gamma    */
           _DOUBLE_SCALAR ,  /* auxc_scal       */
           _DOUBLE_SCALAR ,  /* bmass           */
           _DOUBLE_SCALAR ,  /* boxcutmin       */
           _DOUBLE_SCALAR ,  /* bxctmindg       */
           _DOUBLE_SCALAR ,  /* cd_halfway_freq */
           _DOUBLE_SCALAR ,  /* cd_max_freq     */
           _DOUBLE_SCALAR ,  /* charge          */
           _DOUBLE_SCALAR ,  /* cpus            */
           _DOUBLE_SCALAR ,  /* ddamp           */
           _DOUBLE_SCALAR ,  /* dfpt_sciss      */
           _DOUBLE_SCALAR ,  /* diecut          */
           _DOUBLE_SCALAR ,  /* diegap          */
           _DOUBLE_SCALAR ,  /* dielam          */
           _DOUBLE_SCALAR ,  /* dielng          */
           _DOUBLE_SCALAR ,  /* diemac          */
           _DOUBLE_SCALAR ,  /* diemix          */
           _DOUBLE_SCALAR ,  /* diemixmag       */
           _DOUBLE_SCALAR ,  /* dilatmx         */
           _DOUBLE_SCALAR ,  /* dmft_mxsf       */
           _DOUBLE_SCALAR ,  /* dmft_tolfreq    */
           _DOUBLE_SCALAR ,  /* dmft_tollc      */
           _DOUBLE_SCALAR ,  /* dmftqmc_n       */
           _DOUBLE_SCALAR ,  /* dosdeltae       */
           _DOUBLE_SCALAR ,  /* dtion           */
           _DOUBLE_SCALAR ,  /* ecut            */
           _DOUBLE_SCALAR ,  /* ecuteps         */
           _DOUBLE_SCALAR ,  /* ecutsigx        */
           _DOUBLE_SCALAR ,  /* ecutsm          */
           _DOUBLE_SCALAR ,  /* ecutwfn         */
           _DOUBLE_SCALAR ,  /* effmass_free    */
           _DOUBLE_SCALAR ,  /* efmas_deg_tol   */
           _DOUBLE_SCALAR ,  /* elph2_imagden   */
           _DOUBLE_SCALAR ,  /* eshift          */
           _DOUBLE_SCALAR ,  /* esmear          */
           _DOUBLE_SCALAR ,  /* exchmix         */
           _DOUBLE_SCALAR ,  /* fband           */
           _DOUBLE_SCALAR ,  /* fermie_nest     */
           _DOUBLE_SCALAR ,  /* focktoldfe      */
           _DOUBLE_SCALAR ,  /* freqim_alpha    */
           _DOUBLE_SCALAR ,  /* freqremin       */
           _DOUBLE_SCALAR ,  /* freqremax       */
           _DOUBLE_SCALAR ,  /* freqspmin       */
           _DOUBLE_SCALAR ,  /* freqspmax       */
           _DOUBLE_SCALAR ,  /* friction        */
           _DOUBLE_SCALAR ,  /* fxcartfactor    */
           _DOUBLE_SCALAR ,  /* ga_opt_percent  */
           _DOUBLE_SCALAR ,  /* gwencomp        */
           _DOUBLE_SCALAR ,  /* gwls_model_parameter */
           _DOUBLE_SCALAR ,  /* gw_toldfeig     */
           _DOUBLE_SCALAR ,  /* hyb_mixing      */
           _DOUBLE_SCALAR ,  /* hyb_mixing_sr   */
           _DOUBLE_SCALAR ,  /* hyb_range_dft   */
           _DOUBLE_SCALAR ,  /* hyb_range_fock  */
           _DOUBLE_SCALAR ,  /* kptnrm          */
           _DOUBLE_SCALAR ,  /* kptrlen         */
           _DOUBLE_SCALAR ,  /* magcon_lambda   */
           _DOUBLE_SCALAR ,  /* maxestep        */
           _DOUBLE_SCALAR ,  /* mbpt_sciss      */
           _DOUBLE_SCALAR ,  /* mdf_epsinf      */
           _DOUBLE_SCALAR ,  /* mdwall          */
           _DOUBLE_SCALAR ,  /* mep_mxstep      */
           _DOUBLE_SCALAR ,  /* nelect          */
           _DOUBLE_SCALAR ,  /* noseinert       */
           _DOUBLE_SCALAR ,  /* omegasimax      */
           _DOUBLE_SCALAR ,  /* omegasrdmax     */
           _DOUBLE_SCALAR ,  /* pawecutdg       */
           _DOUBLE_SCALAR ,  /* pawovlp         */
           _DOUBLE_SCALAR ,  /* pawujrad        */
           _DOUBLE_SCALAR ,  /* pawujv          */
           _DOUBLE_SCALAR ,  /* posocc          */
           _DOUBLE_SCALAR ,  /* postoldfe       */
           _DOUBLE_SCALAR ,  /* postoldff       */
           _DOUBLE_SCALAR ,  /* ppmfrq          */
           _DOUBLE_SCALAR ,  /* pw_unbal_thresh */
           _DOUBLE_SCALAR ,  /* ratsph_extra    */
           _DOUBLE_SCALAR ,  /* recrcut         */
           _DOUBLE_SCALAR ,  /* recefermi       */
           _DOUBLE_SCALAR ,  /* rectolden       */
           _DOUBLE_SCALAR ,  /* rhoqpmix        */
           _DOUBLE_SCALAR ,  /* rcut            */
           _DOUBLE_SCALAR ,  /* slabwsrad       */
           _DOUBLE_SCALAR ,  /* slabzbeg        */
           _DOUBLE_SCALAR ,  /* slabzend        */
           _DOUBLE_SCALAR ,  /* spbroad         */
           _DOUBLE_SCALAR ,  /* spinmagntarget  */
           _DOUBLE_SCALAR ,  /* spnorbscl       */
           _DOUBLE_SCALAR ,  /* stmbias         */
           _DOUBLE_SCALAR ,  /* strfact         */
           _DOUBLE_SCALAR ,  /* strprecon       */
           _DOUBLE_SCALAR ,  /* td_maxene       */
           _DOUBLE_SCALAR ,  /* tfw_toldfe      */
           _DOUBLE_SCALAR ,  /* tl_radius       */
           _DOUBLE_SCALAR ,  /* toldfe          */
           _DOUBLE_SCALAR ,  /* tolmxde         */
           _DOUBLE_SCALAR ,  /* toldff          */
           _DOUBLE_SCALAR ,  /* tolimg          */
           _DOUBLE_SCALAR ,  /* tolmxf          */
           _DOUBLE_SCALAR ,  /* tolrde          */
           _DOUBLE_SCALAR ,  /* tolrff          */
           _DOUBLE_SCALAR ,  /* tolsym          */
           _DOUBLE_SCALAR ,  /* tolvrs          */
           _DOUBLE_SCALAR ,  /* tolwfr          */
           _DOUBLE_SCALAR ,  /* tphysel         */
           _DOUBLE_SCALAR ,  /* tsmear          */
           _DOUBLE_SCALAR ,  /* userra          */
           _DOUBLE_SCALAR ,  /* userrb          */
           _DOUBLE_SCALAR ,  /* userrc          */
           _DOUBLE_SCALAR ,  /* userrd          */
           _DOUBLE_SCALAR ,  /* userre          */
           _DOUBLE_SCALAR ,  /* vacwidth        */
           _DOUBLE_SCALAR ,  /* vdw_tol         */
           _DOUBLE_SCALAR ,  /* vdw_tol_3bt     */
           _DOUBLE_SCALAR ,  /* vdw_df_acutmin  */
           _DOUBLE_SCALAR ,  /* vdw_df_aratio   */
           _DOUBLE_SCALAR ,  /* vdw_df_damax    */
           _DOUBLE_SCALAR ,  /* vdw_df_damin    */
           _DOUBLE_SCALAR ,  /* vdw_df_dcut     */
           _DOUBLE_SCALAR ,  /* vdw_df_dratio   */
           _DOUBLE_SCALAR ,  /* vdw_df_dsoft    */
           _DOUBLE_SCALAR ,  /* vdw_df_gcut     */
           _DOUBLE_SCALAR ,  /* vdw_df_phisoft  */
           _DOUBLE_SCALAR ,  /* vdw_df_qcut     */
           _DOUBLE_SCALAR ,  /* vdw_df_qratio   */
           _DOUBLE_SCALAR ,  /* vdw_df_rcut     */
           _DOUBLE_SCALAR ,  /* vdw_df_rsoft    */
           _DOUBLE_SCALAR ,  /* vdw_df_threshold */
           _DOUBLE_SCALAR ,  /* vdw_df_tolerance */
           _DOUBLE_SCALAR ,  /* vdw_df_zab      */
           _DOUBLE_SCALAR ,  /* vis             */
           _DOUBLE_SCALAR ,  /* wfmix           */
           _DOUBLE_SCALAR ,  /* wtq             */
           _DOUBLE_SCALAR ,  /* wvl_hgrid       */
           _DOUBLE_SCALAR ,  /* wvl_crmult      */
           _DOUBLE_SCALAR ,  /* wvl_frmult      */
           _DOUBLE_SCALAR ,  /* xc_denpos       */
           _DOUBLE_SCALAR ,  /* xc_tb09_c       */
           _DOUBLE_SCALAR ,  /* zcut            */
           _DOUBLE_ARRAY  ,  /* boxcenter       */
           _DOUBLE_ARRAY  ,  /* bfield          */
           _DOUBLE_ARRAY  ,  /* dfield          */
           _DOUBLE_ARRAY  ,  /* efield          */
           _DOUBLE_ARRAY  ,  /* genafm          */
           _DOUBLE_ARRAY  ,  /* goprecprm       */
           _DOUBLE_ARRAY  ,  /* neb_spring      */
           _DOUBLE_ARRAY  ,  /* pol             */
           _DOUBLE_ARRAY  ,  /* polcen          */
           _DOUBLE_ARRAY  ,  /* pvelmax         */
           _DOUBLE_ARRAY  ,  /* qptn            */
           _DOUBLE_ARRAY  ,  /* red_efield      */
           _DOUBLE_ARRAY  ,  /* red_dfield      */
           _DOUBLE_ARRAY  ,  /* red_efieldbar   */
           _DOUBLE_ARRAY  ,  /* strtarget       */
           _DOUBLE_ARRAY  ,  /* ucrpa_window    */
           _DOUBLE_ARRAY  ,  /* vcutgeo         */
           _DOUBLE_ARRAY  ,  /* vprtrb          */
           _DOUBLE_ARRAY  ,  /* zeemanfield     */
           _DOUBLE_ARRAY  ,  /* mdtemp          */
           _DOUBLE_ARRAY  ,  /* acell_orig      */
           _DOUBLE_ARRAY  ,  /* amu_orig        */
           _DOUBLE_ARRAY  ,  /* atvshift        */
           _DOUBLE_ARRAY  ,  /* cd_imfrqs       */
           _DOUBLE_ARRAY  ,  /* chempot         */
           _DOUBLE_ARRAY  ,  /* corecs          */
           _DOUBLE_ARRAY  ,  /* densty          */
           _DOUBLE_ARRAY  ,  /* dmatpawu        */
           _DOUBLE_ARRAY  ,  /* efmas_dirs      */
           _DOUBLE_ARRAY  ,  /* f4of2_sla       */
           _DOUBLE_ARRAY  ,  /* f6of2_sla       */
           _DOUBLE_ARRAY  ,  /* gw_qlwl         */
           _DOUBLE_ARRAY  ,  /* gw_freqsp       */
           _DOUBLE_ARRAY  ,  /* gwls_list_proj_freq */
           _DOUBLE_ARRAY  ,  /* jpawu           */
           _DOUBLE_ARRAY  ,  /* kpt             */
           _DOUBLE_ARRAY  ,  /* kptgw           */
           _DOUBLE_ARRAY  ,  /* kptns           */
           _DOUBLE_ARRAY  ,  /* kptns_hf        */
           _DOUBLE_ARRAY  ,  /* mixalch_orig    */
           _DOUBLE_ARRAY  ,  /* mixesimgf       */
           _DOUBLE_ARRAY  ,  /* nucdipmom       */
           _DOUBLE_ARRAY  ,  /* occ_orig        */
           _DOUBLE_ARRAY  ,  /* pimass          */
           _DOUBLE_ARRAY  ,  /* ptcharge        */
           _DOUBLE_ARRAY  ,  /* qmass           */
           _DOUBLE_ARRAY  ,  /* qptdm           */
           _DOUBLE_ARRAY  ,  /* quadmom         */
           _DOUBLE_ARRAY  ,  /* ratsph          */
           _DOUBLE_ARRAY  ,  /* rprim_orig      */
           _DOUBLE_ARRAY  ,  /* rprimd_orig     */
           _DOUBLE_ARRAY  ,  /* shiftk          */
           _DOUBLE_ARRAY  ,  /* shiftk_orig     */
           _DOUBLE_ARRAY  ,  /* spinat          */
           _DOUBLE_ARRAY  ,  /* tnons           */
           _DOUBLE_ARRAY  ,  /* upawu           */
           _DOUBLE_ARRAY  ,  /* vel_cell_orig   */
           _DOUBLE_ARRAY  ,  /* vel_orig        */
           _DOUBLE_ARRAY  ,  /* wtatcon         */
           _DOUBLE_ARRAY  ,  /* wtk             */
           _DOUBLE_ARRAY  ,  /* xred_orig       */
           _DOUBLE_ARRAY  ,  /* xredsph_extra   */
           _DOUBLE_ARRAY  ,  /* ziontypat       */
           _DOUBLE_ARRAY  ,  /* znucl           */
           _INT_SCALAR    ,  /* bs_algorithm    */
           _INT_SCALAR    ,  /* bs_haydock_niter */
           _INT_SCALAR    ,  /* bs_exchange_term */
           _INT_SCALAR    ,  /* bs_coulomb_term */
           _INT_SCALAR    ,  /* bs_calctype     */
           _INT_SCALAR    ,  /* bs_coupling     */
           _INT_SCALAR    ,  /* bs_interp_mode  */
           _INT_SCALAR    ,  /* bs_interp_prep  */
           _INT_SCALAR    ,  /* bs_interp_method */
           _INT_SCALAR    ,  /* bs_interp_rl_nb */
           _DOUBLE_SCALAR ,  /* bs_interp_m3_width */
           _INT_ARRAY     ,  /* bs_interp_kmult */
           _DOUBLE_ARRAY  ,  /* bs_haydock_tol  */
           _INT_ARRAY     ,  /* bs_loband       */
           _DOUBLE_ARRAY  ,  /* bs_eh_cutoff    */
           _DOUBLE_ARRAY  ,  /* bs_freq_mesh    */
           _INT_SCALAR    ,  /* gpu_linalg_limit */
           _INT_SCALAR    ,  /* asr             */
           _INT_SCALAR    ,  /* dipdip          */
           _INT_SCALAR    ,  /* chneut          */
           _INT_SCALAR    ,  /* symdynmat       */
           _INT_SCALAR    ,  /* ph_freez_disp_addstrain */
           _INT_SCALAR    ,  /* ph_freez_disp_option */
           _INT_SCALAR    ,  /* ph_freez_disp_nampl */
           _INT_SCALAR    ,  /* ph_ndivsm       */
           _INT_SCALAR    ,  /* ph_nqpath       */
           _INT_ARRAY     ,  /* ph_ngqpt        */
           _INT_SCALAR    ,  /* ph_nqshift      */
           _INT_SCALAR    ,  /* ph_             */
           _DOUBLE_ARRAY  ,  /* ph_freez_disp_ampl */
           _DOUBLE_ARRAY  ,  /* ph_qshift       */
           _DOUBLE_ARRAY  ,  /* ph_qpath        */
           _DOUBLE_SCALAR ,  /* eph_mustar      */
           _INT_SCALAR    ,  /* eph_intmeth     */
           _DOUBLE_SCALAR ,  /* eph_extrael     */
           _DOUBLE_SCALAR ,  /* eph_fermie      */
           _INT_SCALAR    ,  /* eph_frohlichm   */
           _DOUBLE_SCALAR ,  /* eph_fsmear      */
           _DOUBLE_SCALAR ,  /* eph_fsewin      */
           _INT_ARRAY     ,  /* eph_ngqpt_fine  */
           _INT_SCALAR    ,  /* eph_transport   */
           _INT_SCALAR    ,  /* ph_intmeth      */
           _DOUBLE_SCALAR ,  /* ph_wstep        */
           _DOUBLE_SCALAR ,  /* ph_smear        */
           _INT_ARRAY     ,  /* ddb_ngqpt       */
           _DOUBLE_ARRAY  ,  /* ddb_shiftq      */
           _INT_SCALAR    ,  /* ndivsm          */
           _INT_SCALAR    ,  /* nkpath          */
           _DOUBLE_ARRAY  ,  /* einterp         */
           _DOUBLE_ARRAY  ,  /* kptbounds       */
           _DOUBLE_ARRAY  ,  /* tmesh           */
           _OTHER         
};

#endif
