#!/usr/bin/env python
from __future__ import annotations

__version__ = "1.0"
__author__ = "Matteo Giantomassi"

import argparse
import html
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Callable, Iterator
from os.path import abspath as absp
from os.path import basename
from os.path import join as pj
from socket import gethostname
from typing import Any
from warnings import warn

# The ConfigParser module has been renamed to configparser in Python 3
from configparser import ConfigParser as SafeConfigParser
from configparser import NoOptionError


# Set ABI_PSPDIR env variable to point to the absolute path of Pspdir
os.environ["ABI_PSPDIR"] = os.path.abspath(os.path.join(os.path.dirname(__file__), "Pspdir"))

# Add the directory [...]/abinit/tests to $PYTHONPATH
pack_dir, x = os.path.split(absp(__file__))
pack_dir, x = os.path.split(pack_dir)
sys.path.insert(0, pack_dir)
import tests

_my_name = basename(__file__) + "-" + __version__

abitests = tests.abitests
abenv = tests.abenv

from pymods import termcolor
from pymods.jobrunner import JobRunner, OMPEnvironment, TimeBomb
from pymods.testsuite import BuildEnvironment
from pymods.tools import pprint_table


def lazy__str__(func: Callable) -> Callable:
    """
    Decorator that provides a default __str__ implementation based on object attributes.

    Args:
        func (callable): The function to decorate.

    Returns:
        callable: The wrapped function.
    """
    def oncall(*args, **kwargs):
        self = args[0]
        return "\n".join(str(k) + " : " + str(v) for (k, v) in self.__dict__.items())
    return oncall


def _yesno2bool(string: str) -> bool:
    """
    Convert "yes"/"no" strings to boolean.

    Args:
        string: String to convert.

    Returns:
        bool: True if "yes", False if "no".

    Raises:
        ValueError: If the string cannot be interpreted.
    """
    string = string.lower().strip().replace('"', "").replace("'", "")
    if string == "yes":
        return True
    if string == "no":
        return False
    raise ValueError("Cannot interpret string: %s" % string)

def _str2list(string: str | list[str] | tuple[str, ...]) -> list[str]:
    """
    Parse a comma-separated string into a list of trimmed strings.

    Args:
        string: The string or list/tuple to process.

    Returns:
        list: A list of trimmed strings.
    """
    if isinstance(string, (list, tuple)):
        return string

    return [s.strip() for s in string.split(",") if s]

def get_mpi_prefix_from_env() -> str | None:
    """
    Try to detect the MPI installation directory from environment variables.

    Checks MPI_HOME and MPIHOME. This is used for compatibility with certain
    Buildbot worker configurations.

    Returns:
        str | None: The detected MPI path, or None if not found.
    """
    # This is what JMB does in buildbot_worker/testbot.py
    # The problem is that this has precedence over mpi_prefix. Should ask why!!
    try:
       return os.environ["MPI_HOME"]
    except Exception:
       pass
    try:
       return os.environ["MPIHOME"]
    except Exception:
        pass

    return None


class TestBot:
    """
    Driver for ABINIT automatic tests on Buildbot workers.

    The execution flow consists of:
    1. Loading configuration from `testbot.cfg` (INI, generated by abibuildbot).
    2. Initializing `JobRunner` instances for sequential and parallel execution.
    3. Selecting and running test suites based on selected keywords and tags.
    4. Aggregating results into a summary report.
    """
    _attrbs = {
      # name           --> (default, parser, info)
      # If default is None, the option must be specified.
      "builder_name"     : (None, str, "Name of buildbot builder"),
      "type"             : ("",   str, "'ref' if this builder is a reference builder where all tests should pass"),
      "max_cpus"         : (None, int, "Max number of CPUs that can be used by TestBot"),
      "max_gpus"         : (0,    int, "Max number of GPUs that can be used by TestBot"),
      "mpi_prefix"       : ("",   str, "MPI runner"),
      "mpirun_np"        : ("",   str, "String used to execute `mpirun -n#NUM`"),
      "omp_num_threads"  : (0,    int, "Number of OpenMP threads. 0 if OpenMP should not be used"),
      "enable_mpi"       : (None, _yesno2bool, "yes if MPI is activated else no."),
      "enable_openmp"    : (None, _yesno2bool, "yes if OpenMP is activated else no."),
      "with_tdirs"       : ("", _str2list, "List of subsuites to include."),
      "without_tdirs"    : ("", _str2list, "List of subsuites to exclude."),
      "timeout_time"     : (1200, float, "Timeout time in seconds."),
      "runmode"          : ("static", str, "'static to run all tests with 1 MPI proc and use np > 1 only for multiparallel tests'"),
      "keywords"         : ("", _str2list, "String with the keywords that should be selected/ignored."),
      "verbose"          : (0,    int, "Verbosity level"),
      "tmp_basedir"      : ("", str, "Temporary folder where the tests will be executed and copied back"),
      "mpi_args"         : ("", str, "Args passed to the mpi command"),
      "force_mpi"        : ("no", _yesno2bool, "Force usage of mpirun_np prefix"),
    }

    @classmethod
    def print_options(cls) -> None:
        """
        Print the available configuration options with descriptions and defaults.
        """
        for opt_name, t in cls._attrbs.items():
            default, parser, info = t
            print("#", info)
            print(opt_name, "=", default)

        print("# NB If default is None, the option must be specified.")

    def __init__(self, testbot_cfg: str | None = None) -> None:
        """
        Initialize the TestBot instance.

        Args:
            testbot_cfg: Optional path to the INI configuration file.

        Raises:
            ValueError: If mandatory options are missing or invalid.
        """
        attrs2read = [
            "builder_name",
            "type",
            "max_cpus",
            "max_gpus",
            "mpi_prefix",
            "mpirun_np",
            "omp_num_threads",
            "with_tdirs",
            "without_tdirs",
            "timeout_time",
            "runmode",
            "keywords",
            "verbose",
            "tmp_basedir",
            "mpi_args",
            "force_mpi",
        ]

        # Read the options specified in the testbot configuration file.
        if testbot_cfg is None:
            basedir, _ = os.path.split(absp(__file__))
            testbot_cfg = pj(basedir, "testbot.cfg")

        # Here we init the attributes either from the cfg file
        parser = SafeConfigParser()
        parser.read(testbot_cfg)

        for attr in attrs2read:
            default, parse, info = TestBot._attrbs[attr]
            try:
                value = parser.get("testbot", attr)
            except NoOptionError:
                value = default

            if value is None:
                # Write out the cfg file and raise
                for section in parser.sections():
                    print("[" + section + "]")
                    for opt in parser.options(section):
                        print(opt + " = " + parser.get(section, opt))
                raise ValueError("Mandatory option %s is not declared" % attr)

            self.__dict__[attr] = parse(value)

        if self.with_tdirs and self.without_tdirs:
            raise ValueError("with_tdirs and without_tdirs attribute are mutually exclusive")

        if self.type not in ["", "ref"]:
            raise ValueError(f"type should be either 'ref' or empty string while it's: {self.type}")

        system, node, release, version, machine, processor = platform.uname()
        print("Running on %s -- builder %s (type: %s) -- system %s -- max_cpus %s -- Python %s -- %s" % (
              gethostname(), self.builder_name, self.type or "regular", system, self.max_cpus,
              platform.python_version(), _my_name))

        # 2) Initialize the job_runner.
        self.build_env = build_env = BuildEnvironment(os.curdir)
        self.build_env.set_buildbot_builder(self.builder_name)

        # Consistency check between input parameters and build configuration.
        if "HAVE_GPU" not in self.build_env.defined_cppvars:
            if self.max_gpus > 0:
                warn(
                    f"Builder {self.builder_name} requested max_gpus={self.max_gpus} but was "
                    "not compiled with GPU support; forcing max_gpus=0"
                )
            self.max_gpus = 0
        elif self.max_gpus <= 0:
            raise ValueError(
                f"Builder {self.builder_name} was compiled with GPU support "
                f"but max_gpus is {self.max_gpus}"
            )

        if "HAVE_OPENMP" not in self.build_env.defined_cppvars and self.omp_num_threads > 2:
            warn(
                f"Builder {self.builder_name} requested omp_num_threads={self.omp_num_threads} "
                "but was not compiled with OpenMP support; clamping to 2"
            )
            self.omp_num_threads = 2

        if build_env.has_bin("timeout") and self.timeout_time > 0:
            # We can run executables under the control of timeout.c
            timeout_path = build_env.path_of_bin("timeout")
            timebomb = TimeBomb(self.timeout_time, exec_path=timeout_path)
        else:
            warn("Cannot find timeout executable at: %s" % build_env.path_of_bin("timeout"))
            timebomb = TimeBomb(self.timeout_time)

        print("Initalizing JobRunner for sequential runs.")
        self.seq_runner = JobRunner.sequential(timebomb=timebomb)
        print(self.seq_runner)

        if self.has_mpi:
            print("Initalizing MPI JobRunner from self.__dict__")
            self.mpi_runner = JobRunner.fromdict(self.__dict__, timebomb=timebomb)
            print(self.mpi_runner)

        if self.omp_num_threads > 0:
            print("Initalizing OMP environment with omp_num_threads %d " % self.omp_num_threads)
            omp_env = OMPEnvironment(OMP_NUM_THREADS=self.omp_num_threads)
            self.seq_runner.set_ompenv(omp_env)
            if self.has_mpi:
                self.mpi_runner.set_ompenv(omp_env)

        print(self)

        # Initialize the table to store the final results.
        # The table include all the abinit tests (also those that will be skipped)
        # values are initialized with None.
        # FIXME
        database = abitests.get_database()
        res_table = database.init_result_table()
        self.summary = TestBotSummary(res_table)
        #print(self.summary)

    def __str__(self) -> str:
        """String representation."""
        lines = []
        app = lines.append
        for attr_name, t in self._attrbs.items():
            default, parser, info = t
            value = getattr(self, attr_name, "undefined")
            app("%s = %s" % (attr_name, value))

        return "\n".join(lines)

    @property
    def has_mpi(self) -> bool:
        """bool: True if an MPI runner is configured."""
        return bool(self.mpirun_np)

    @property
    def has_openmp(self) -> bool:
        """bool: True if tests should be executed with OpenMP."""
        return self.omp_num_threads > 0

    def run_tests_with_np(self, mpi_nprocs: int, suite_args: list[str] | str | None = None, runmode: str = "static") -> tuple[int, int, int]:
        """
        Run a subset of tests using a specified number of MPI processes.

        Calculates the appropriate number of parallel Python processes based on
        available CPUs and OpenMP configuration.

        Args:
            mpi_nprocs: Number of MPI processes per test.
            suite_args: Arguments for test suite selection.
            runmode: Execution mode ("static" or "parallel").

        Returns:
            tuple: (nfailed, npassed, nexecuted)
        """
        # Compute number of python processes, note that self.omp_num_threads might be zero.
        py_nprocs = self.max_cpus // (mpi_nprocs * max(self.omp_num_threads, 1))
        if py_nprocs < 1:
            raise RuntimeError("py_nprocs = %s" % py_nprocs)

        test_suite = abitests.select_tests(suite_args, keys=self.keywords, regenerate=False)

        # Create workdir.
        workdir_name = "TestBot_MPI" + str(mpi_nprocs)
        if self.has_openmp:
            workdir_name += "_OMP" + str(self.omp_num_threads)

        if os.path.exists(workdir_name):
            raise RuntimeError("%s already exists!" % workdir_name)
        os.mkdir(workdir_name)

        if self.tmp_basedir:
            workdir = os.path.join(tempfile.mkdtemp(dir=self.tmp_basedir), workdir_name)
        else:
            workdir = workdir_name

        # Run the tests.
        if self.has_openmp:
            msg = "Running ntests = %s, MPI_nprocs = %s, OMP_nthreads %s, Max GPUs: %s, py_nprocs = %s..." % (
                  test_suite.full_length, mpi_nprocs, self.omp_num_threads, self.max_gpus, py_nprocs)
        else:
            msg = "Running ntests = %s, MPI_nprocs = %s, Max GPUs: %s py_nprocs = %s..." % (
                  test_suite.full_length, mpi_nprocs, self.max_gpus, py_nprocs)
        print(msg)

        job_runner = self.seq_runner
        if mpi_nprocs > 1 or self.force_mpi:
            job_runner = self.mpi_runner

        results = test_suite.run_tests(self.build_env, workdir, job_runner,
                                       mpi_nprocs=mpi_nprocs,
                                       omp_nthreads=self.omp_num_threads,
                                       max_cpus=self.max_cpus,
                                       max_gpus=self.max_gpus,
                                       py_nprocs=py_nprocs,
                                       runmode=self.runmode,
                                       verbose=self.verbose,
                                       make_html_diff=1)

        if results is None:
            print("Test suite is empty, returning 0 0 0 ")
            return 0, 0, 0

        # Store the results in the summary table,
        # taking into account that an input file might be executed multiple times
        # with a different environment (MPI, OMP ...)
        self.summary.merge_results(test_suite)

        if self.tmp_basedir:
            for fn in ["results.tar.gz", "index.html"]:
                try:
                    shutil.copy2(os.path.join(workdir, fn), workdir_name)
                except Exception:
                    print("Could not copy back file ", fn)

        return results.nfailed, results.npassed, results.nexecuted

    def run(self) -> int:
        """
        Execute the full test suite based on the current configuration.

        This method handles:
        - Running sequential and/or parallel tests.
        - Executing multi-parallel suites with varying CPU counts.
        - Generating the final summary table and JSON report.

        Returns:
            int: Number of failed tests (or total passed + failed for reference builders).
        """
        # TODO
        #import multiprocessing
        #multiprocessing.set_start_method("fork")  # Ensure compatibility on macOS/Linux

        # Disable colors
        termcolor.enable(False)

        # If with_tdirs and without_tdirs are not given => execute all tests.
        # else create a list of strings with the suites that should be executed|excluded.
        suite_args = None

        # XG130410 Crude hack, to avoid paral and mpiio test directories
        # in case of enable_mpi=no in config/specs/testfarm.conf
        if not self.has_mpi:
            suite_args = "paral- mpiio-".split()

        if self.with_tdirs:
            suite_args = self.with_tdirs

        elif self.without_tdirs:
            # Append "-" to the string to signal that the suite should be excluded.
            suite_args = "- ".join([s for s in self.without_tdirs]) + "-"
            suite_args = suite_args.split()

        if self.runmode == "static":
            # Old mode: run all available tests with 1 MPI proc here,
            # then use MPI mode in mp_suites (paral/mpiio)
            np_list = [2, 4, 8, 10, 24, 64]
            #nfailed, npassed, nexecuted = 0, 0 , 0
            nfailed, npassed, nexecuted = self.run_tests_with_np(1, suite_args=suite_args, runmode=self.runmode)
        else:
            # New mode: run all available tests with 2 MPI procs here,
            # then enter the mp_suites with np_list CPUs
            np_list = [4, 8, 10, 24, 64]
            nfailed, npassed, nexecuted = self.run_tests_with_np(2, suite_args=suite_args, runmode=self.runmode)

        if self.has_mpi:
            # Run the parallel tests in the multi-parallel suites.
            mp_suites = abitests.multi_parallel_suites()
            suite_args = [suite.name for suite in mp_suites]

            # Prune dirs.
            if self.with_tdirs:
                suite_args = [s for s in self.with_tdirs if s in suite_args]

            elif self.without_tdirs:
                suite_args = [s for s in suite_args if s not in self.without_tdirs]

            for np in np_list:
                if np > self.max_cpus or not suite_args:
                    print("Skipping tests with np: %s as max_cpus: %s" % (np, self.max_cpus))
                    continue

                print("Running multi-parallel tests with %s MPI processors, suite_args %s" % (np, suite_args))
                para_nfailed, para_npassed, para_nexec = self.run_tests_with_np(np, runmode="static", suite_args=suite_args)

                # Accumulate the counters.
                nfailed += para_nfailed
                npassed += para_npassed
                nexecuted += para_nexec

        table = self.summary.to_table()
        #pprint_table(table)

        self.summary.json_dump("testbot_summary.json")

        # Post-process the summary now, in-process (produces testbot_analysis.html
        # and records the git tag). analyze()'s own return code is deliberately
        # not propagated here -- post-processing must never override the real
        # test result (self.type/nfailed/npassed below).
        try:
            analyze_rc = analyze("testbot_summary.json", tag=get_git_tag())
            if analyze_rc != 0:
                print(f"analyze() returned {analyze_rc}")
        except Exception as exc:
            print(f"analyze() raised an exception: {exc}")

        # Empty list of tests (usually due to the use of with, without options)
        # Create file to signal this condition and return 0.
        if nexecuted == 0:
            print("No file found")
            with open("__emptylist__", "w") as fh:
                fh.write("nfailed = %d, npassed = %d, nexecuted = %d" % (nfailed, npassed, nexecuted))
                return 0

        # The status error depends on the builder type.
        if self.type == "ref":
            # Reference builder --> all the tests must pass.
            return nfailed + npassed

        return nfailed


def get_git_tag() -> str:
    """
    Return the output of `git describe --tags --abbrev=0`, or "unknown" on failure.

    Mirrors the fallback used in builder_scripts/analysis.sh
    (`git describe --tags --abbrev=0 2>/dev/null || echo "unknown"`).
    """
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"


def analyze(fname: str, tag: str = "unknown") -> int:
    """
    Analyze and display the performance figures of the tests.

    Parses the summary JSON file and prints a table with execution times
    (CPU and Wall) per test suite. This is the in-process equivalent of the
    post-processing previously embedded as a Python heredoc in
    builder_scripts/analysis.sh (kept there as an independent fallback).

    Also writes an HTML <table> fragment (no <html>/<head>/<body>) with the
    same data to "testbot_analysis.html" in the current directory, for
    embedding into the results index page (see upload_results.sh).

    Args:
        fname: Path to the JSON summary file.
        tag: Git tag/revision to record in the summary JSON.

    Returns:
        int: 0 on success. Non-zero on failure (1 if the summary file is
            missing or incomplete, 99 for any other post-processing error),
            matching the historical analysis.sh exit codes.
    """
    if not os.path.exists(fname):
        print(f"Error: {fname} not found. Analysis failed.")
        with open("ANALYSIS_SUMMARY_FAILED", "w") as f:
            f.write(f"{fname} missing")
        return 1

    try:
        with open(fname) as data_file:
            d = json.load(data_file)

        d["tag"] = tag
        with open(fname, "w") as data_file:
            json.dump(d, data_file)

        if "summary_table" not in d:
            print("Error: 'summary_table' missing in JSON.")
            with open("ANALYSIS_SUMMARY_FAILED", "w") as f:
                f.write("summary_table missing")
            return 1

        tests_status = dict(zip(d["summary_table"][0], d["summary_table"][1]))

        dashline = "=" * 74
        print(dashline)
        print("      Series   #failed   #passed  #success  #skip  |   #CPU      #WALL")
        print(dashline)

        paral, mpiio = "", ""
        html_rows = []
        for t, s in sorted(tests_status.items()):
            skip_series = True
            rtime = ttime = 0.0

            if t in d and isinstance(d[t], dict):
                for test_info in d[t].values():
                    if test_info.get("status") != "skipped":
                        skip_series = False
                        rtime += test_info.get("run_etime", 0.0)
                        ttime += test_info.get("tot_etime", 0.0)

            if not skip_series:
                counts = "".join("%5s   |" % v for v in s.split("/"))
                row = "%12s | %s %7.1f  | %7.1f" % (t, counts, rtime, ttime)
                if t == "mpiio":
                    mpiio = row
                elif t == "paral":
                    paral = row
                else:
                    print(row)

                nfailed_s = s.split("/")[0]
                row_class = "suite-failed" if nfailed_s not in ("0", "") else "suite-ok"
                cells = "".join(f"<td>{html.escape(v)}</td>" for v in s.split("/"))
                html_rows.append(
                    f'<tr class="{row_class}"><td>{html.escape(t)}</td>{cells}'
                    f"<td>{rtime:.1f}</td><td>{ttime:.1f}</td></tr>"
                )

        print(dashline)
        if paral:
            print(paral)
        if mpiio:
            print(mpiio)
        if paral or mpiio:
            print(dashline)

        html_table = (
            '<table id="testbot-summary" class="testbot-summary" border="1" cellpadding="4" cellspacing="0">'
            "<thead><tr><th>Series</th><th>#failed</th><th>#passed</th><th>#success</th>"
            "<th>#skip</th><th>#CPU (s)</th><th>#WALL (s)</th></tr></thead>"
            "<tbody>"
            + "".join(html_rows)
            + "</tbody></table>"
        )
        with open("testbot_analysis.html", "w") as f:
            f.write(html_table)

        return 0

    except Exception as exc:
        print(f"Post-processing failed: {exc}")
        with open("ANALYSIS_SUMMARY_FAILED", "w") as f:
            f.write(str(exc))
        return 99


class TestBotSummary:
    """
    Aggregates and formats the final results of a TestBot run.

    This class maintains a result table for all test suites and provides methods
    to merge new results and export them to various formats (HTML, JSON).
    """

    _possible_status = ["failed", "passed", "succeeded", "skipped"]

    def __init__(self, res_table: dict[str, dict[str, Any]]) -> None:
        self.res_table = res_table
        self.failed = []
        self.passed = []

    @lazy__str__
    def __str__(self) -> str:
        """
        Default string representation.
        """

    def _min_status(self, items: list[str]) -> str:
        indices = [self._possible_status.index(item) for item in items]
        return self._possible_status[min(indices)]

    def to_table(self) -> list[list[str]]:
        """
        Convert the current summary into a table format for display.

        The table contains suite names and their corresponding pass/fail/skip stats.

        Returns:
            list[list[str]]: A list of rows, where each row is a list of strings.
        """
        def stats2string(stats):
            """Helper function that returns (nfail/npass/nsucc/nskipped)"""
            return "/".join(str(stats[k]) for k in self._possible_status)

        table = [self.suite_names()]
        rows = []
        for suite_name in self:
            status, stats = self.status_of_suite(suite_name)
            rows.append(stats2string(stats))
        table.append(rows)

        return table

    def merge_results(self, test_suite: Any) -> None:
        """
        Merge results from a completed test suite into the global summary.

        Updates the status of each test (e.g., marking as failed if any run failed)
        and accumulates execution times.

        Args:
            test_suite: The executed test suite object.
        """
        # assert test_suite._executed
        for test in test_suite:
            d = self.res_table[test.suite_name][test.id]

            if "status" not in d:
                # Entry is not initialized. Save the status of this test.
                d["status"] = test.status
                d["number_of_runs"] = 1
                d["run_etime"] = test.run_etime
                d["tot_etime"] = test.tot_etime
            else:
                # Handle the case where we have executed the same test but with a different setup.
                # Ordering is: failed < passed < succeeded
                # hence a test is marked as "failed" if at least one run failed.
                d["status"] = self._min_status([test.status, d["status"]])
                d["number_of_runs"] += 1
                d["run_etime"] += test.run_etime
                d["tot_etime"] += test.tot_etime

        # Store the full_id of the tests that (failed|passed).
        for test in test_suite.failed_tests():
            self.failed.append(test.full_id)

        for test in test_suite.passed_tests():
            self.passed.append(test.full_id)

    def __iter__(self) -> Iterator[str]:
        """Iterate over the suite names in alphabetical order."""
        for suite_name in self.suite_names():
            yield suite_name

    def suite_names(self) -> list[str]:
        """List of suite names in alphabetical order."""
        return sorted(list(self.res_table.keys()))

    def status_of_suite(self, suite_name: str) -> tuple[str, dict[str, int]]:
        """
        Args:
            suite_name: string with the name of the suite.

        return: (suite_status, stats) where
            suite_status is one of the possile status in `_possible_status`
            stats is a dictionary : {failed:1, passed:2, succeeded:0, skipped:0}
        """
        # Initialize stats setting the keys to 0
        stats = dict.fromkeys(self._possible_status, 0)

        for test_id, d in self.res_table[suite_name].items():
            if "status" not in d:
                d["status"] = "skipped"
            stats[d["status"]] += 1

        for status in self._possible_status:
            if stats[status] > 0:
                suite_status = status
                break
        else:
            # Ignore error if suite is empty else raise.
            if not self.res_table[suite_name]:
                suite_status = "succeeded"
            else:
                raise RuntimeError("[%s] Wrong list of status values!" % suite_name)

        return suite_status, stats

    def json_dump(self, fname: str) -> None:
        """
        Export the current summary to a JSON file.

        The exported data includes a list of failed tests, passed tests, and
        the detailed result table for all suites.

        Args:
            fname: Path to the output JSON file.
        """
        # list of strings with the name of the tests that (failed|passed)
        d = {}
        d["failed"] = self.failed
        d["passed"] = self.passed
        d["summary_table"] = self.to_table()

        for suite_name in self:
            #print("---", suite_name, self.res_table[suite_name])
            if suite_name in d:
                #raise KeyError("Cannot overwrite key %s" % suite_name)
                print("Warning: About to overwrite key %s" % suite_name)
            d[suite_name] = self.res_table[suite_name]

        with open(fname, "w") as fh:
            json.dump(d, fh)


def build_parser() -> argparse.ArgumentParser:
    """
    Build the command-line argument parser for TestBot.

    Returns:
        argparse.ArgumentParser: The configured parser with `run`, `analyze`,
        and `print` subcommands.
    """
    parser = argparse.ArgumentParser(
        prog="testbot.py",
        description="Driver for ABINIT automatic tests on Buildbot workers.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    run_parser = subparsers.add_parser(
        "run", help="Run the test suite described by a testbot.cfg file."
    )
    run_parser.add_argument(
        "testbot_cfg",
        nargs="?",
        default=None,
        help="Path to the testbot.cfg INI file (default: testbot.cfg next to this script).",
    )

    analyze_parser = subparsers.add_parser(
        "analyze", help="Analyze an existing testbot_summary.json and print a timing table."
    )
    analyze_parser.add_argument(
        "tag",
        nargs="?",
        default="unknown",
        help="Git tag/revision to record in the summary (default: unknown).",
    )

    print_parser = subparsers.add_parser(
        "print",
        help="Parse a testbot.cfg and print the resulting configuration without running any tests.",
    )
    print_parser.add_argument(
        "testbot_cfg",
        nargs="?",
        default=None,
        help="Path to the testbot.cfg INI file (default: testbot.cfg next to this script).",
    )

    return parser


def main() -> int:
    """
    Main entry point for TestBot's command-line interface.

    Returns:
        int: The exit code of the execution.
    """
    args = build_parser().parse_args()

    if args.command == "analyze":
        return analyze(fname="testbot_summary.json", tag=args.tag)

    # "run" and "print" both parse a testbot.cfg into a TestBot instance.
    if args.testbot_cfg is not None:
        print("Reading testbot.cfg configuration file from: ", args.testbot_cfg)

    # Disable colors
    termcolor.enable(False)

    testbot = TestBot(args.testbot_cfg)

    if args.command == "print":
        print(testbot)
        return 0

    return testbot.run()


if __name__ == "__main__":
    sys.exit(main())
