#!/bin/sh

version="1.2"
patch_number="0003"

autoconf
mkdir wannier90-${version}.old wannier90-${version}.new
mv configure wannier90-${version}.new
cp wannier90-${version}.mk wannier90-${version}.old/Makefile
echo "all_targets all: wannier lib" >wannier90-${version}.new/Makefile
cat wannier90-${version}.mk >>wannier90-${version}.new/Makefile
echo "include ./make.sys" >>wannier90-${version}.new/Makefile
diff -urN wannier90-${version}.old wannier90-${version}.new \
  >../../patches/wannier90-${version}-${patch_number}.patch
rm -rf autom4te.cache configure wannier90-${version}.old wannier90-${version}.new
