# ===========================================
# Makefile.src
# Generic make file to be used when
#  building LIBPAW library
#                                M.T. june 13
# ===========================================

include ../../makefile.in

all:

default:

clean:
	@rm -rf *.o *.mod

%.o: %.F90
	$(FC) ${FCFLAGS} $(INCS) -o $(@F) -c $<
%.o: %.c
	$(CC) ${CFLAGS} $(INCS) -o $(@F) -c $<

